ethereum-optimism/ecosystem

apps/bridge-app/package.json, packages/op-app/package.json, pnpm-lock.yaml
* Bump `wagmi` & `viem` to `^2.0.0`
=> Bump Wagmi & Viem to v2

.github/workflows/main.yml
* Adds github action for unit tests
* Setup foundry as part of the action
=> Add Github Action for Unit Tests

apps/bridge-app/README.md
=> Add bridge-app README

apps/bridge-app/src/components/AccountMenu.tsx
Fixes https://github.com/ethereum-optimism/ecosystem/security/code-scanning/1 and https://github.com/ethereum-optimism/ecosystem/security/code-scanning/2
=> fix code scanning issues

packages/op-app/src/configs/networkPairs.ts, packages/op-app/supportedL1Networks.json
* Drops Goerli Support. Generated from `pnpm nx run @eth-optimism/op-app:codegen`.
=> Drops Goerli Support

README.md
Adding reference to developer forum (preferred route for devrel)
=> Update support to mention Dev Forum

apps/bridge-app/src/components/AccountMenu.tsx, apps/bridge-app/src/components/NetworkSelector.tsx, apps/bridge-app/src/components/bridge/From.tsx, apps/bridge-app/src/components/bridge/To.tsx, apps/bridge-app/src/components/bridge/TokenListDialog.tsx, apps/bridge-app/src/routes/Bridge.tsx
Updated some styles from the components in `bridge-app`
=> Update misc styles in bridge-app

.circleci/config.yml
branch filters need to be defined at the job level
=> fix(ci): fix branch filters for docker build and publish

apps/dapp-console/app/components/Header/HeaderTab.tsx, apps/dapp-console/app/components/Header/index.tsx, apps/dapp-console/app/constants/index.tsx, apps/dapp-console/app/insights/page.tsx, apps/dapp-console/app/lib/utils.ts, apps/dapp-console/app/page.tsx, apps/dapp-console/package.json, pnpm-lock.yaml
- Adds navigation menu items to the header + switches pages when clicking the `<Links>`
- Brought in the `cn` lib utility to conditionally apply classnames using tailwind classes
=> feat(dapp-console): Implement navigation menu

apps/dapp-console/app/components/Tile/Tile.tsx, apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/components/LaunchSection.tsx, apps/dapp-console/app/page.tsx
closes: https://github.com/ethereum-optimism/ecosystem/issues/87, https://github.com/ethereum-optimism/ecosystem/issues/88
Implemented a local `Tile` component in the dapp-console project. I may bring some version of this into `ui-components` later on but for now i am using the Card component and modifying some of the classes with tailwind.
Also implemented the build section of the dapp console
=> Implement Tile component + build section

package.json, pnpm-lock.yaml
A clear and concise description of the features you're adding in this pull request.
**Tests**
Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
=> Rollback NX Version

apps/dapp-console/app/console/components/ProjectIconLinks.tsx, apps/dapp-console/app/constants/index.tsx, packages/ui-components/src/components/ui/dialog.tsx, packages/ui-components/src/components/ui/tooltip.tsx
Implemented the superchain icon modal + tooltip interaction on the dapp console homepage. Both are using our `ui-components` from the design system.
Also brought in the dates + urls for docs items from the [PRD doc here](https://docs.google.com/document/d/1iJeKa9o3cRnIO0yxxwnDgFaP8nr_hocsBKr6tDlWKD0/edit)
https://github.com/ethereum-optimism/ecosystem/assets/10838132/be995da0-1407-454a-9d01-c18f5d251cdc
=> Implement Superchain icon modal + tooltip interaction

apps/dapp-console/app/components/Header/HeaderTabs.tsx, apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/components/LaunchSection.tsx, apps/dapp-console/app/console/components/SupportSection.tsx, apps/dapp-console/app/constants/index.tsx, apps/dapp-console/app/helpers/index.ts
Implemented support section modal + refactored the way that the docsItemLinks are consumed.
https://github.com/ethereum-optimism/ecosystem/assets/10838132/77c80275-fbc9-41ab-8d21-81281b4ee29e
=> Implement support section modal + refactor links

apps/dapp-console/app/insights/page.tsx, apps/dapp-console/app/page.tsx
Implementation of the Insights page
=> Insights page

apps/event-log-indexer/.eslintignore, apps/event-log-indexer/.gitignore, apps/event-log-indexer/.prettierignore, apps/event-log-indexer/abis/optimist.ts, apps/event-log-indexer/package.json, apps/event-log-indexer/ponder-env.d.ts, apps/event-log-indexer/ponder.config.ts, apps/event-log-indexer/ponder.schema.ts, apps/event-log-indexer/src/constants/contracts.ts, apps/event-log-indexer/src/constants/networks.ts, apps/event-log-indexer/src/events/optimist.ts, apps/event-log-indexer/src/index.ts, apps/event-log-indexer/tsconfig.json, packages/op-app/src/test-utils/setup.ts, pnpm-lock.yaml
Adds the initial implementation of our new indexing service. More can be found out about the structure over on this issue https://github.com/ethereum-optimism/ecosystem/issues/127. This PR only contains everything thats needed to run locally, the next PR we put up will contain all of the docker logic along with running postgres locally.
=> Adds event-log-indexer

packages/api-plugin/src/generators/trpc-api-generator/files/package.json, packages/api-plugin/src/generators/trpc-api-generator/files/src/Service.ts, packages/api-plugin/src/generators/trpc-api-generator/files/src/api/Api.ts, packages/api-plugin/src/generators/trpc-api-generator/files/src/monitoring/metrics.ts
Adds prometheus metrics to trpc-api-generator
=> Add prometheus metrics to trpc-api-generator

apps/paymaster-proxy/package.json, apps/paymaster-proxy/src/ProxyService.ts, apps/paymaster-proxy/src/initializeApiServer.ts, pnpm-lock.yaml
- make server log all http requests.
- using morgan, same as our base services
=> feat(paymaster-proxy): add logging for all requests

apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/components/LaunchSection.tsx, apps/dapp-console/app/console/components/ProjectIconLinks.tsx, apps/dapp-console/app/console/components/PromotionsSection.tsx, apps/dapp-console/app/console/useDialogContent.tsx, apps/dapp-console/app/constants/index.tsx, apps/dapp-console/app/layout.tsx, packages/ui-components/src/components/ui/badge.tsx
Addressing various issues outlined in the bugbash including:
- Adding success variant to the Badge component
- Fixing mobile modal issue
- Update frax date to correct date
- Update Promotions title to Deals
- Hide learn more buttons in Deals modals if not signed in
- Update frax link
- Update page title
=> fix(dapp console): Various bugbash fixes

apps/dapp-console/app/settings/components/LinkedWallet.tsx, apps/dapp-console/app/settings/wallets/page.tsx, apps/dapp-console/package.json, pnpm-lock.yaml
=> Adds Unlink Wallet Flow

apps/dapp-console/app/console/SuperchainSafeModalContent.tsx, apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/components/ProjectIconLinks.tsx, apps/dapp-console/app/console/constants.tsx, apps/dapp-console/app/console/useDialogContent.tsx, apps/dapp-console/app/constants/index.tsx
Adding in the multistep superchain safe modal to dapp console
https://github.com/ethereum-optimism/ecosystem/assets/10838132/fe4727ee-2723-4764-b4e8-ebf4f7be10dc
=> feat(dapp-console): Add in superchain safe multistep modal

apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/constants.tsx, apps/dapp-console/app/console/useDialogContent.tsx, apps/dapp-console/app/constants/index.tsx
closes https://github.com/ethereum-optimism/ecopod/issues/902
Add in the quick start guide card to the build section outlined in this issue
https://github.com/ethereum-optimism/ecopod/issues/902
=> feat(dapp-console): Add in quick start guide to build section

apps/dapp-console/app/components/Header/index.tsx, apps/dapp-console/app/console/SuperchainSafeModalContent.tsx, apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/components/LaunchSection.tsx, apps/dapp-console/app/console/components/SupportSection.tsx, apps/dapp-console/app/console/constants.tsx, apps/dapp-console/app/constants/index.tsx, apps/dapp-console/app/page.tsx, apps/dapp-console/app/seo/index.tsx, apps/dapp-console/app/settings/layout.tsx
Going from dapp to app on the copy of the site.
=> Replace all instances of dapp to app, adding lisk, update rpgf to retro funding

apps/dapp-console-api/src/Service.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/872
This PR makes the following changes to how the dapp-console-api service starts:
1. brings up the express server prior to running the server migrations
2. registers the `/healthz` endpoint so that argocd knows the server has been started
3. registers the `/ready` endpoint that initially returns an error response so argo knows the service is not ready for traffic
4. attempts the migrations on the sql database with a retry + backoff
5. if the migrations succeed, mark the service as initialized so that the `/ready` endpoint returns a success response
=> feat(dapp-console-api): refactor how migrations are run on dapp-console-api

apps/dapp-console/app/constants/index.tsx, apps/dapp-console/app/globals.css, apps/dapp-console/app/providers/PrivyProviderWrapper.tsx
Update privy modal to have the community agreement instead of privacy policy
=> Update community agreement for privy modal

.github/CODEOWNERS, docs/superchain-paymaster/README.md
also adds @zainbacchus to CODEOWNERS to be able to approve docs PRs
=> fix(docs): add rpc urls to docs

apps/dapp-console/app/console/constants.tsx, apps/dapp-console/app/constants/index.tsx
=> Add link to demo apps for testnet paymaster

apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/constants.tsx, apps/dapp-console/app/seo/index.tsx
Updating copy for this issue + updating the og:image
=> Update copy + meta image

apps/dapp-console/app/settings/components/WalletVerificationMethods.tsx
Adds links for the wallet verification methods on the settings page
=> Adds links for wallet verification methods

apps/ui-component-storybook/.storybook/main.ts, apps/ui-component-storybook/.storybook/preview.tsx, apps/ui-component-storybook/package.json, pnpm-lock.yaml
Adding dark mode to the storybook setup
=> Adding dark mode to storybook

apps/ui-component-storybook/package.json
making the modification needed to setup storybook app deployment
=> Change storybook package name for deployment setup

apps/dapp-console-api/migrations/0001_icy_lilith.sql, apps/dapp-console-api/migrations/0001_spicy_spitfire.sql, apps/dapp-console-api/migrations/meta/0001_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/package.json, apps/dapp-console-api/src/models/addresses.ts, apps/dapp-console-api/src/models/index.ts, pnpm-lock.yaml
Closes https://github.com/ethereum-optimism/ecopod/issues/875
=> feat(dapp-console): create address data model

apps/dapp-console/app/settings/account/page.tsx, apps/dapp-console/package.json, pnpm-lock.yaml
This PR finishes up all the pieces on the accounts page, all that is left is hooking it up against the backend.
Desktop view
Mobile view
Delete User
Update Email
=> Adds support for editing email and deleting user

apps/dapp-console/app/seo/index.tsx, packages/ui-components/src/style.css
Fixing the modal overflow not being able to scroll when the screen size is less than the modal content height
=> fix(ui-components): Modal overflow bug

apps/ui-component-storybook/package.json
A clear and concise description of the features you're adding in this pull request.
**Tests**
Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.
**Additional context**
Add any other context about the problem you're solving.
**Metadata**
- Fixes #[Link to Issue]
=> changing storybook package name

apps/ui-component-storybook/.storybook/main.ts, apps/ui-component-storybook/.storybook/preview.tsx, apps/ui-component-storybook/README.md, apps/ui-component-storybook/package.json, packages/ui-components/README.md, pnpm-lock.yaml
Adding the README for Storybook
=> Adding readme and setup for storybook

apps/dapp-console/app/console/constants.tsx, apps/dapp-console/app/settings/components/ClaimedRebateProgressBanner.tsx, apps/dapp-console/app/settings/components/ClaimedRebates.tsx, apps/dapp-console/app/settings/components/CoinbaseVerificationBanner.tsx, apps/dapp-console/app/settings/components/LinkedWallet.tsx, apps/dapp-console/app/settings/components/RebateDialog.tsx, apps/dapp-console/app/settings/components/SettingsCard.tsx, apps/dapp-console/app/settings/components/WalletVerificationMethods.tsx, apps/dapp-console/app/settings/contracts/DApp.tsx, apps/dapp-console/app/settings/contracts/DApps.tsx, apps/dapp-console/app/settings/contracts/page.tsx, apps/dapp-console/app/settings/layout.tsx, apps/dapp-console/app/settings/wallets/page.tsx, apps/dapp-console/package.json, packages/ui-components/src/components/ui/progress/progress.tsx, pnpm-lock.yaml
This PR starts to implement the contracts page. It adds all of the components needed outside of the app section which will be done in a follow on PR.
This is an overview of what the page looks like right now
Variant of what it looks like if the progress bar has any progress
=> Contracts Page Shell

apps/ui-component-storybook/README.md, packages/ui-components/README.md
Modifying the storybook and component library readme's
=> modify storybook readme

apps/dapp-console-api/migrations/0002_neat_star_brand.sql, apps/dapp-console-api/migrations/meta/0002_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/models/apps.ts, apps/dapp-console-api/src/models/index.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/911
=> feat(dapp-console): create app data model

apps/dapp-console-api/migrations/0003_slimy_arachne.sql, apps/dapp-console-api/migrations/meta/0003_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/models/index.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/876
=> feat(dapp-console): create contract model

apps/dapp-console-api/migrations/0005_last_carmella_unuscione.sql, apps/dapp-console-api/migrations/meta/0005_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/models/deploymentRebates.ts, apps/dapp-console-api/src/models/index.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/896
=> feat(dapp-console): create deployment rebates model

apps/dapp-console-api/migrations/0006_steep_deadpool.sql, apps/dapp-console-api/migrations/meta/0006_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/models/challenges.ts, apps/dapp-console-api/src/models/index.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/878
=> feat(dapp-console): challenges data model

apps/api-key-service/.eslintrc.cjs, apps/api-key-service/.gitignore, apps/api-key-service/README.md, apps/api-key-service/example.env, apps/api-key-service/package.json, apps/api-key-service/project.json, apps/api-key-service/src/Service.ts, apps/api-key-service/src/Trpc.ts, apps/api-key-service/src/api/Api.ts, apps/api-key-service/src/api/ApiV0.ts, apps/api-key-service/src/api/Middleware.ts, apps/api-key-service/src/api/index.ts, apps/api-key-service/src/cmd/run.ts, apps/api-key-service/src/constants/cors.ts, apps/api-key-service/src/constants/envVars.ts, apps/api-key-service/src/constants/index.ts, apps/api-key-service/src/constants/types.ts, apps/api-key-service/src/index.ts, apps/api-key-service/src/monitoring/metrics.ts, apps/api-key-service/src/routes/Route.ts, apps/api-key-service/src/routes/index.ts, apps/api-key-service/tsconfig.json, apps/api-key-service/tsup.config.ts, apps/api-key-service/vitest.config.ts, pnpm-lock.yaml, tsconfig.base.json
creates new trpc api service for the api-key-service
mostly uses the trpc-api generator but changes up how we do dependency injection for metrics / logger since we no longer have to do hacky "setLoggingServer"
if changes look good i can change the generator files as well
=> feat(api-key-service): create new app

.circleci/config.yml, Dockerfile, apps/api-key-service/docker-compose.yml, apps/api-key-service/package.json
- creates dockerfile
- creates docker-compose file
- push build to artifact registry with circleci
=> build(api-key-service): update dockerfile and docker-compose

apps/dapp-console/app/constants/toast.ts, apps/dapp-console/app/settings/components/LinkedWallet.tsx, apps/dapp-console/app/settings/contracts/AddContractCard.tsx, apps/dapp-console/app/settings/contracts/AddContractForm.tsx, apps/dapp-console/app/settings/contracts/DApp.tsx, apps/dapp-console/app/settings/contracts/StartVerificationDialog.tsx, apps/dapp-console/package.json, apps/dapp-console/tailwind.config.ts, pnpm-lock.yaml
* Adds form on for being able to add a new contract
* Adds dialog flow for being able to verify a contract manually
* Updates accordion animations to also include opacity and not just height
* Adds a constant file for toast durations 
https://github.com/ethereum-optimism/ecosystem/assets/1761993/731caf09-a2fc-472c-b5b9-2b4f969e5320
=> [dapp console] Add Contract & Verification Flows

apps/dapp-console/app/console/useDialogContent.tsx, apps/dapp-console/app/event-tracking/mixpanel.tsx
Adding in new tracking hooks for mixpanel to measure the connect wallet buttons in the modals.
More info can be found here: https://docs.google.com/document/d/1iJeKa9o3cRnIO0yxxwnDgFaP8nr_hocsBKr6tDlWKD0/edit
=> Adding in new signInModal tracking hooks

apps/dapp-console/app/console/components/LaunchSection.tsx
=> Fix copy on Retro Funding

apps/dapp-console-api/package.json, apps/dapp-console/app/constants/envVars.ts, apps/dapp-console/app/helpers/apiClient.ts, apps/dapp-console/app/layout.tsx, apps/dapp-console/app/settings/wallets/page.tsx, apps/dapp-console/package.json, pnpm-lock.yaml
* Setup `@trpc/next` wrapper
* Adds `NEXT_PUBLIC_API_URL` env var, this is where we'll read the base api url from
* Adds our `syncWallets` call to test communicating with the backend
* Syncs all `trpc` versions across the api and FE to `^10.45.2`
=> [dapp console] Setup API Client with @trpc/next

apps/dapp-console-api/migrations/0010_condemned_sasquatch.sql, apps/dapp-console-api/migrations/meta/0010_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/models/transactions.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/917
=> feat(dapp-console-api): add block timestamp column to transactions table

apps/dapp-console-api/src/models/apps.ts, apps/dapp-console-api/src/models/wallets.ts, apps/dapp-console-api/src/monitoring/metrics.ts, apps/dapp-console-api/src/routes/apps/AppsRoute.ts, apps/dapp-console-api/src/routes/wallets/WalletsRoute.spec.ts, apps/dapp-console-api/src/utils/privy.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/925
`editApp` endpoint is used for letting a user edit the name of their app.
=> feat(dapp-console-api): `editApp` endpoint

apps/dapp-console-api/migrations/0011_absurd_salo.sql, apps/dapp-console-api/migrations/meta/0011_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/package.json, apps/dapp-console-api/src/api/zodHelpers.ts, apps/dapp-console-api/src/constants/chains.ts, apps/dapp-console-api/src/constants/index.ts, apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/monitoring/metrics.ts, apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts, pnpm-lock.yaml
`createContract` endpoint is used for creating a new contract within an app.
=> feat(dapp-console-api): `createContract` endpoint

apps/dapp-console-api/src/models/wallets.ts
Fixes a bug in how the `updateWallet` function was updating wallets in the database.
=> feat(dapp-console-api): fix updateWallet

apps/dapp-console-api/migrations/0014_brave_rictor.sql, apps/dapp-console-api/migrations/meta/0014_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/api/zodHelpers.ts, apps/dapp-console-api/src/models/challenges.ts, apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/monitoring/metrics.ts, apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
Adds `completeVerification` endpoint to the `contracts` route. This endpoint handles completing a challenge for the user when they are going through the contract verification flow.
=> feat(dapp-console-api): `completeVerification` endpoint

apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/routes/apps/AppsRoute.ts, apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts, apps/dapp-console-api/src/routes/utils.ts, apps/dapp-console-api/src/routes/wallets/WalletsRoute.ts
Adds `getContract`  endpoint for fetching a single contract from db.
=> feat(dapp-console-api): `getContract` endpoint

apps/dapp-console-api/src/models/transactions.ts, apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
Insert deployment transaction into database upon creation of a new contract.
=> feat(dapp-console-api): insert deployment transaction into db

apps/dapp-console-api/src/db/Database.ts, apps/dapp-console-api/src/models/apps.ts, apps/dapp-console-api/src/models/challenges.ts, apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/models/deploymentRebates.ts, apps/dapp-console-api/src/models/entities.ts, apps/dapp-console-api/src/models/schema.ts, apps/dapp-console-api/src/models/transactions.ts, apps/dapp-console-api/src/models/utils.ts, apps/dapp-console-api/src/models/wallets.ts, apps/dapp-console-api/src/routes/apps/AppsRoute.ts
This PR defines the database schema with relationships in order to allow for db queries to include joins to other tables. Drizzle documentation: https://orm.drizzle.team/docs/rqb
=> feat(dapp-console-api): configure db relations

apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/console/components/LaunchSection.tsx, apps/dapp-console/app/console/constants.tsx
=> Remove UX feedback and User feedback

apps/dapp-console-api/example.env, apps/dapp-console-api/migrations/0017_loud_prima.sql, apps/dapp-console-api/migrations/meta/0017_snapshot.json, apps/dapp-console-api/migrations/meta/_journal.json, apps/dapp-console-api/src/Service.ts, apps/dapp-console-api/src/constants/chains.ts, apps/dapp-console-api/src/constants/envVars.ts, apps/dapp-console-api/src/constants/rebates.ts, apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/models/deploymentRebates.ts, apps/dapp-console-api/src/models/transactions.ts, apps/dapp-console-api/src/models/utils.ts, apps/dapp-console-api/src/monitoring/metrics.ts, apps/dapp-console-api/src/routes/apps/AppsRoute.ts, apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts, apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts, apps/dapp-console-api/src/utils/rebateEligibility.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/895
`claimDeploymentRebate` handles distributing deployment rebate to eligible address.
=> feat(dapp-console-api): `claimDeploymentRebate` endpoint

apps/dapp-console-api/example.env, apps/dapp-console-api/src/Service.ts, apps/dapp-console-api/src/api/zodHelpers.ts, apps/dapp-console-api/src/constants/chains.ts, apps/dapp-console-api/src/constants/envVars.ts, apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
Updates the dapp-console-api to support the latest list of chains.
=> feat(dapp-console-api): update supported chains

apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
Registers the `listCompletedRebates` in it's route file
=> Registers the list rebates endpoint

apps/dapp-console/app/components/Badges/HexBadge.tsx, apps/dapp-console/app/components/Badges/NetworkBadge.tsx, apps/dapp-console/app/components/Network.tsx, apps/dapp-console/app/components/Selects/L2NetworkSelect.tsx, apps/dapp-console/app/constants/rebate.ts, apps/dapp-console/app/constants/superchain.ts, apps/dapp-console/app/lib/utils.ts, apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx, apps/dapp-console/app/settings/components/ClaimedRebateProgressBanner.tsx, apps/dapp-console/app/settings/components/ClaimedRebates.tsx, apps/dapp-console/app/settings/components/EligibleForRebateBadge.tsx, apps/dapp-console/app/settings/components/IneligibleRebateDialog.tsx, apps/dapp-console/app/settings/components/NeedsVerificationBadge.tsx, apps/dapp-console/app/settings/components/NotEligibleForRebateBadge.tsx, apps/dapp-console/app/settings/contracts/AddContractFlow.tsx, apps/dapp-console/app/settings/contracts/AddContractForm.tsx, apps/dapp-console/app/settings/contracts/DeployedApp.tsx, apps/dapp-console/app/settings/contracts/DeployedAppContract.tsx, apps/dapp-console/app/settings/contracts/StartVerificationDialog/FinishVerificationContent.tsx, apps/dapp-console/app/settings/contracts/page.tsx, apps/dapp-console/app/types/api.ts, packages/op-app/src/utils/address.ts
* Adds a `HexBadge` component used for displaying any sort of hex with a label and the shortened version of the hex
* Adds a `NetworkBadge` component that takes in a chain id and will display the chain name and it's logo
* Adds a `Network` component this is a general purpose component used that displays the chain name and logo in a flex row, it's being used in other components that need network info
* Adds a `superchain.ts` file that contains all the superchain defs. We'll eventually move this to a common pkg.
* Updates contract creation flow to use relations returned in request
* Updates rebate flows to be integrated with backend except the claim mutation
* Update our api types to be inferred from the backend, still not crazy about how it's being inferred something we'll …
=> Rebate Flows

apps/dapp-console-api/src/models/apps.ts, apps/dapp-console-api/src/models/contracts.ts, apps/dapp-console-api/src/monitoring/metrics.ts, apps/dapp-console-api/src/routes/apps/AppsRoute.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/925
=> feat(dapp-console-api): delete app endpoint

apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts, apps/dapp-console/app/helpers/errorReporting.ts, apps/dapp-console/app/settings/contracts/DeleteContractDialog/DeleteContractContent.tsx, apps/dapp-console/app/settings/contracts/DeleteContractDialog/SuccessContent.tsx, apps/dapp-console/app/settings/contracts/DeleteContractDialog/index.tsx, apps/dapp-console/app/settings/contracts/DeployedApp.tsx, apps/dapp-console/app/settings/contracts/DeployedAppContract.tsx
* Adds `DeleteContractDialog` along with it's start step, and success step
* Updates `DeployedApp` to show/hide the dialog when we have something to delete
* Registers delete contract route on backend
=> Adds Delete Contract Flow

apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx, apps/dapp-console/app/settings/contracts/AddContractForm.tsx, apps/dapp-console/app/settings/contracts/StartVerificationDialog/FinishVerificationContent.tsx, apps/dapp-console/app/types/api.ts
* Updates error handling for creating/verifying contracts, and claiming rebates to use custom codes returned from trpc api
* Updates finish verification dialog to use `react-form-hook` so we don't need to implement any extra logic for showing/hiding errors and having buttons disabled/enabled
=> Updates form to place errors under specific field or button

apps/dapp-console/app/components/Badges/CoinbaseVerificationBadge.tsx, apps/dapp-console/app/components/Selects/L2NetworkSelect.tsx, apps/dapp-console/app/helpers/errorReporting.ts, apps/dapp-console/app/lib/utils.ts, apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx, apps/dapp-console/app/settings/components/ClaimedRebateProgressBanner.tsx, apps/dapp-console/app/settings/components/ClaimedRebates.tsx, apps/dapp-console/app/settings/components/LinkedWallet.tsx, apps/dapp-console/app/settings/components/WalletVerificationMethods.tsx, apps/dapp-console/app/settings/contracts/AddContractForm.tsx, apps/dapp-console/app/settings/contracts/AppActionsDropdown.tsx, apps/dapp-console/app/settings/contracts/DeployedApp.tsx, apps/dapp-console/app/settings/contracts/DeployedAppContract.tsx, apps/dapp-console/app/settings/contracts/DeployedApps.tsx, apps/dapp-console/app/settings/contracts/EditAppDialog.tsx, apps/dapp-console/app/settings/wallets/page.tsx
* Adds function to only display ether values up to 8 decimals and strips trailing zeros
* Adjusts styles to prevent any sort of collisions or overlaps on mobile
* Adds Coinbase Verification badge to wallets page
* Adds Delete App Flow
* Adds loading state to wallet link/unlink flows
=> Design cleanup

apps/dapp-console-api/src/constants/envVars.ts, apps/dapp-console-api/src/middleware/getRateLimiter.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/987
=> feat(dapp-console-api): add rate limit window env var

apps/dapp-console-api/src/middleware/isPrivyAuthed.ts, apps/dapp-console-api/src/routes/auth/AuthRoute.ts, apps/dapp-console-api/src/utils/auth.ts, apps/dapp-console-api/src/utils/index.ts, apps/dapp-console/app/components/Header/SignInButton.tsx, apps/dapp-console/app/helpers/errorReporting.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/986
=> feat(dapp-console-api): loginUser endpoint

apps/dapp-console-api/src/monitoring/metrics.ts, apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/984
=> feat(dapp-console-api): track deployment rebate wallet balance

apps/dapp-console/app/components/Header/SignInButton.tsx, apps/dapp-console/app/constants/superchain.ts, apps/dapp-console/app/settings/components/CoinbaseVerificationBanner.tsx, apps/dapp-console/app/settings/components/SettingsMenu.tsx, apps/dapp-console/app/settings/components/WalletVerificationMethods.tsx, apps/dapp-console/app/settings/contracts/AddContractFlow.tsx, apps/dapp-console/app/settings/contracts/AddContractForm.tsx, apps/dapp-console/app/settings/contracts/DeployedApp.tsx, apps/dapp-console/app/settings/contracts/DeployedApps.tsx, apps/dapp-console/app/settings/contracts/StartVerificationDialog/BeginContent.tsx, apps/dapp-console/app/settings/contracts/StartVerificationDialog/StartVerificationContent.tsx, apps/dapp-console/app/settings/contracts/page.tsx, apps/dapp-console/app/settings/wallets/page.tsx
* Adds a hard refresh to `/` when the user signs out
* Fix text typos
* Updates `AddContractForm` to clear transaction hash not found errors when we switch the network
* Fixes mobile settings menu background color when the dark theme is selected
* Renames `Optimism` network to `OP Mainnet`
* Adds link to coinbase docs on `CoinbaseVerificationBanner`
* Updates wallet page to only render wallets that are also linked to the users privy account
* Updates `StartVerificationDialog` to fetch the challenge on the first screen and move loading/error states over to that screen, along with a retry toast
* Removes OP NFT from `WalletVerifications` and updates language around how often testnet funds are distributed in the faucet
* Updates some header styles and updates them to use …
=> Dev Console M2 Bugbash Bug Fixes

apps/dapp-console/app/console/components/PromotionsSection.tsx
In the PromotionsSection component's div, the class list was modified to include 'flex-wrap'. This change modifies the layout behavior to allow wrapping of child elements if there isn't enough space within the container.
=> Fix scroll clipping on categories

apps/api-key-service/src/index.ts, apps/api-key-service/src/routes/keys/KeysRoute.ts, apps/paymaster-proxy/docker-compose.yml, apps/paymaster-proxy/src/ProxyService.ts, apps/paymaster-proxy/src/adminApi/createAdminRouter.ts, apps/paymaster-proxy/src/adminApi/initializeAdminApiServer.ts, apps/paymaster-proxy/src/apiKeyService/createApiKeyServiceClient.ts, apps/paymaster-proxy/src/envVarsSchema.ts, apps/paymaster-proxy/src/models/sponsorshipPolicies.ts, apps/paymaster-proxy/src/paymasterProvider/alchemy/AlchemyGasManagerAdminClient.ts
accidentally based it to wrong branch (instead of `main`)
original PR: https://github.com/ethereum-optimism/ecosystem/pull/319
=> fix(paymaster-proxy): fix merge issue

apps/dapp-console/app/event-tracking/mixpanel.tsx, apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx, apps/dapp-console/app/settings/contracts/AddContractForm.tsx, apps/dapp-console/app/settings/contracts/DeleteContractDialog/index.tsx, apps/dapp-console/app/settings/contracts/DeployedApp.tsx, apps/dapp-console/app/settings/contracts/DeployedApps.tsx, apps/dapp-console/app/settings/contracts/StartVerificationDialog/FinishVerificationContent.tsx, apps/dapp-console/app/settings/wallets/page.tsx
* Adds general tracking functions for clicks, and confirmations related to apps, contracts, and wallets
* Adds tracking for rebate clicks & confirmations
* Adds tracking for start/finish contract verification
* Adds tracking for the connector type used when linking wallets
=> Dev Console M2 Tracking

apps/dapp-console/app/console/components/Announcements.tsx, apps/dapp-console/app/console/components/LaunchSection.tsx, apps/dapp-console/app/hooks/useFeatureFlag.ts, apps/dapp-console/app/settings/contracts/DeployedAppContract.tsx, apps/dapp-console/app/settings/contracts/page.tsx, apps/dapp-console/app/settings/layout.tsx
Closes https://github.com/ethereum-optimism/ecopod/issues/1018
=> feat(dapp-console): deployment rebate growthbook flag

apps/dapp-console/app/settings/contracts/AddContractForm.tsx
Hides testnet prop on network selector
=> Hide testnets

apps/dapp-console/app/components/Auth/RequireLogin.tsx, apps/dapp-console/app/components/Header/SignInButton.tsx, apps/dapp-console/app/settings/layout.tsx
This PR makes the following changes:
- Creates `RequireLogin` wrapper component that requires a user to be authenticated in order to view the children of the component.
- Wraps the Settings page in the `RequireLogin` component
=> feat(dapp-console): `RequireLogin` component

apps/paymaster-proxy/src/adminApi/createAdminRouter.ts, apps/paymaster-proxy/src/api/createV1ApiRouter.ts, apps/paymaster-proxy/src/config/chainConfigByChainId.ts, apps/paymaster-proxy/src/envVarsSchema.ts
=> feat(paymaster-proxy): add more chains

docs/superchain-paymaster/README.md
closes https://github.com/ethereum-optimism/ecopod/issues/958
=> docs(paymaster): add new chains to docs

packages/contracts-ecosystem/script/ConfigureFaucetDrippie.s.sol, packages/contracts-ecosystem/script/DeployFaucetDrippie.s.sol
Closes https://github.com/ethereum-optimism/ecopod/issues/996
=> feat(faucet): foundry scripts for deploying and configuring faucet drippie

packages/contracts-ecosystem/script/DeployFaucet.s.sol, packages/contracts-ecosystem/script/DeployFaucetDrippie.s.sol, packages/contracts-ecosystem/script/DeployHelper.sol
This PR does not change any functionality on the deployment scripts. Just cleans them up and adds a helper library.
=> feat(faucet): improvements to faucet deployment scripts

apps/dapp-console/app/faucet/components/Faqs.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/page.tsx, packages/ui-components/src/components/ui/accordian/accordion.tsx, packages/ui-components/src/components/ui/radio-group/radio-card.tsx
Adding in all the inputs for the faucet.
- Network radio card selection
- Address input
- FAQs from the old faucet (for now)
=> feat(faucet): Add input field + network selection + FAQ section

apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/components/LearnMoreDialogContent.tsx, apps/dapp-console/app/faucet/components/LogoChain.tsx, packages/ui-components/src/components/ui/input/input.tsx
Adding in the Learn more dialog to the UI. Also fixed a few ui bugs.
=> feat(faucet): Add in the learn more dialog

apps/dapp-console/app/faucet/components/AuthenticationCard.tsx, apps/dapp-console/app/faucet/components/FaucetHeader.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/components/LogoChain.tsx, apps/dapp-console/app/faucet/page.tsx
Updated design & implementation for the faucet authentication methods. Since we can use world ID or onchain verification I made this more prominent on the UI vs the previous design.
Also hooked up the auth on the connect wallet & sign in button to work with an actual account.
=> feat(faucet): Update login flow UI

apps/dapp-console/app/faucet/components/AuthenticationCard.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/page.tsx, apps/dapp-console/app/utils/index.tsx
Adding form validation to faucet UI + fixing mobile styles
=> feat(faucet): Add form validation to faucet UI

.changeset/honest-fireants-relate.md, packages/sdk/tsconfig.json
* Updates `module` & `target` to match what it was set on it the optimism repo
=> Update SDK build

packages/message-queue/.gitignore, packages/message-queue/package.json, packages/message-queue/src/config/QueueConfig.ts, packages/message-queue/src/config/QueueJobParams.ts, packages/message-queue/src/examples/example-config.ts, packages/message-queue/src/examples/example-queue.ts, packages/message-queue/src/examples/example-worker.ts, packages/message-queue/src/index.ts, packages/message-queue/src/job-processor/JobProcessor.ts, packages/message-queue/src/queue/Queue.ts, packages/message-queue/src/queue/createQueue.ts, packages/message-queue/src/utils/parseRedisConnectionString.ts, packages/message-queue/src/worker/Worker.ts, packages/message-queue/src/worker/createWorker.ts, packages/message-queue/tsconfig.json, packages/message-queue/tsup.config.ts, pnpm-lock.yaml
thin wrapper around bullmq that 
- enforces namespaces
- adds basic logging
- adds better typing job job name/data
- adds JobProcessor - a convenience class that lets you set up handlers easily / typesafe way
- see `/examples` for usage examples
=> feat(message-queue): create message-queue package

apps/dapp-console-api/src/routes/auth/AuthRoute.ts
=> Adding route for Gitcoin

apps/dapp-console-api/src/routes/faucet/FaucetRoute.ts, apps/dapp-console/app/faucet/components/ClaimButton.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/faucet/helpers.ts, apps/dapp-console/app/hooks/useFaucetVerifications.ts
Refactored the ClaimButton logic to prioritize onchain authentications and integrate faucet verifications.
- Reorganized the ClaimButton logic to get onchain authentication in order of priority and fallback to WORLD_ID if none found.
- Introduced a new return value in `useFaucetVerifications` to fetch the seconds until the next faucet drip based on the user's authentication status.
- Updated the FaucetContent component to utilize the `useFaucetVerifications` hook and manage countdown state based on the next drip time.
=> feat(faucetl): Wire up countdown

apps/dapp-console/app/faucet/components/ClaimButton.tsx, apps/dapp-console/app/faucet/components/Faqs.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/components/SuccessDialog.tsx, apps/dapp-console/app/faucet/page.tsx, apps/dapp-console/app/hooks/useFaucetVerifications.ts
Enhanced the faucet feature by adding a block explorer URL callback, making UI improvements in multiple components for better responsiveness.
1. **ClaimButton Component**: Added `setBlockExplorerUrl` prop to handle setting the block explorer URL after a successful claim.
2. **SuccessDialog Component**: Updated UI to display a 'View transaction' button with a link to the block explorer.
3. **Faqs, FaucetContent, FaucetHeaderInner Components**: Various UI improvements for better responsiveness and user interaction.
=> feat(faucet): Clean up success modal + various style fixes

apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/hooks/useFaucetVerifications.ts
Disables user interactions (such as input fields and network selection) when the timer is active.
- Added Alert component to display a countdown timer.
- Disabled input fields and buttons when countdown is active or user is not authenticated.
- Cleaned up `useFaucetVerifications` to remove unnecessary logs and simplify `nextDrips` query.
=> feat(faucet): Add disabled states for authentication & claim successful 

apps/dapp-console/app/faucet/components/ClaimButton.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/hooks/useFaucetVerifications.ts, apps/dapp-console/package.json, pnpm-lock.yaml
Adding worldID functionality to the faucet
=> Adding world

apps/dapp-console/app/faucet/components/ClaimButton.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/components/SuccessDialog.tsx, apps/dapp-console/app/hooks/useFaucetVerifications.ts
Refactor and enhance the claim process in the faucet components, adding and updating states and behavior. Removed console logs and refetched drips while a claim is in progress.
1. Removed unnecessary console logs from various components.
2. Added `isClaimInProgress` state to manage claim processing.
3. Updated `SuccessDialog` component to handle different states of claim processing.
4. Modified `FaucetContent` component to refetch drips information while a claim is in progress.
5. Refactored `useFaucetVerifications` hook to include multiple authentication checks and drip refetching.
6. Enhanced the claim button and countdown text logic.
=> feat(faucet): Implement tx loading state

apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/faucet/components/Faqs.tsx, apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx, apps/dapp-console/app/faucet/components/LearnMoreDialogContent.tsx, apps/dapp-console/app/hooks/useFaucetVerifications.ts
closes https://github.com/ethereum-optimism/ecopod/issues/1070 https://github.com/ethereum-optimism/ecopod/issues/1072 https://github.com/ethereum-optimism/ecopod/issues/1078
This pull request updates the FAQ accordion items in the faucet component. Specifically, it changes the testnet reference from 'OP Goerli' to 'OP Sepolia'. Additionally, the FAQ item about supported test networks was removed.
=> fix(faucet): Update FAQs, add authentication check, learn more links & loading state

apps/dapp-console/app/event-tracking/mixpanel.tsx, apps/dapp-console/app/faucet/components/ClaimButton.tsx, apps/dapp-console/app/faucet/page.tsx, apps/dapp-console/app/faucet/types.ts
closes https://github.com/ethereum-optimism/ecopod/issues/1082
This PR introduces Mixpanel tracking for faucet claims.
- Introduced new Mixpanel tracking events and properties for faucet claims in `mixpanel.tsx`
- Updated `ClaimButton.tsx` to include tracking functionality
- Removed unnecessary feature flag check in the `Faucet` component in `page.tsx`
=> feat(faucet): Add mixpanel tracking to claim button

apps/dapp-console/app/console/components/BuildSection.tsx, apps/dapp-console/app/faucet/components/Faqs.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/faucet/components/FaucetHeader.tsx, apps/dapp-console/app/faucet/page.tsx, apps/dapp-console/app/seo/index.tsx
1. **Authentications Refactor**: The `authentications` prop has been removed from `FaucetContent`, `FaucetHeader`, and parent components. Instead, authentication data is now retrieved using the `useFaucetVerifications` hook.
2. **Add 'use client' Directive**: The 'use client' directive has been added to several components to ensure they are treated as client components.
3. **Metadata Update**: Added metadata for the faucet page, including title and description for better SEO.
=> fix(faucet): Update SEO

apps/bridge-app/index.html, apps/bridge-app/src/App.tsx, apps/bridge-app/src/components/tictactoe/CreateGameDialog.tsx, apps/bridge-app/src/components/tictactoe/Game.tsx, apps/bridge-app/src/components/tictactoe/JoinGameDialog.tsx, apps/bridge-app/src/constants/contracts.ts, apps/bridge-app/src/hooks/tictactoe/useCreateGame.ts, apps/bridge-app/src/hooks/tictactoe/useGameState.ts, apps/bridge-app/src/hooks/tictactoe/useJoinGame.ts, apps/bridge-app/src/hooks/tictactoe/useMakeMove.ts, apps/bridge-app/src/providers/TicTacToeProvider.tsx, apps/bridge-app/src/routes/TicTacToe.tsx, apps/bridge-app/src/utils/tictactoe.ts, apps/bridge-app/tailwind.config.js
Implements FE for TicTacToe. This was largely tested by switching accounts in the same browser with metamask so there will need to be some polish around loading states and stuff but figured we can focus on that if we care once we get the interop portion working.
Tracker: https://github.com/ethereum-optimism/supersim/issues/3
**Create Game**
**Join Game**
**Board**
=> TicTacToe UI

apps/kyc-faq/index.html
Updating the page title in the FAQ page
=> Update page title in FAQs

apps/kyc-faq/src/App.tsx
Removing react router from code.
=> remove react router

apps/kyc-faq/src/constants.tsx
update contact support url
Update constants.tsx
=> fix(kyc): Update contact support url

apps/dapp-console/app/faucet/components/FaucetMaintenance.tsx, apps/dapp-console/app/faucet/components/FaucetPage.tsx, apps/dapp-console/app/faucet/page.tsx
Updating the faucet to include maintenance mode when the `enable_console_faucet` flag is flipped off.
=> fix(faucet): Add maintenance mode to faucet

packages/viem/src/actions/buildExecuteL2ToL2Message.spec.ts, packages/viem/src/actions/buildExecuteL2ToL2Message.ts, packages/viem/src/actions/estimateExecuteL2ToL2MessageGas.spec.ts, packages/viem/src/actions/estimateExecuteL2ToL2MessageGas.ts, packages/viem/src/actions/executeL2ToL2Message.spec.ts, packages/viem/src/actions/executeL2ToL2Message.ts, packages/viem/src/actions/sendL2ToL2Message.spec.ts, packages/viem/src/utils/extractMessageIdentifierFromLogs.ts
Adds all the actions needed to execute interop messages
**L2 Public Actions**
* `buildExecuteL2ToL2Message`
* `estimateExecuteL2ToL2MessageGas`
**L2 Wallet Actions**
* `executeL2ToL2Message`
**Utils**
* `extractMessageIdentifierFromLogs`
=> Adds actions to execute interop messages

apps/dapp-console/app/page.tsx
closes https://github.com/ethereum-optimism/growth/issues/56
Removed the Announcements component from the dapp-console page.
=> Remove devconsole banner

apps/dapp-console-api/src/routes/auth/AuthRoute.ts, apps/dapp-console-api/src/utils/getGitcoinPassportAttestation.ts
This fixes the score calcualtion for gitcoin passport
=> Fix gitcoin score calc

packages/viem/src/index.ts, packages/viem/src/utils/extractMessageIdentifierFromLogs.ts
Updates `@eth-optimism/viem` to include all exports for functions, types, and constants that we want to be public for whomever is consuming the package.
=> Adds public interop exports

packages/viem/README.md, packages/viem/docs/actions/buildExecuteL2ToL2Message.md, packages/viem/docs/actions/buildSendL2ToL2Message.md, packages/viem/docs/actions/estimateExecuteL2ToL2MessageGas.md, packages/viem/docs/actions/estimateSendL2ToL2MessageGas.md, packages/viem/docs/actions/executeL2ToL2Message.md, packages/viem/docs/actions/sendL2ToL2Message.md, packages/viem/docs/guides/interop.md, packages/viem/docs/utils/extractMessageIdentifierFromLogs.md
* Adds initial `README` with intro and links to docs
* Adds first pass at docs for all actions and utils
* Adds interop guide which shows an e2e code snippet
=> @eth-optimism/viem docs

packages/viem/src/abis.ts, packages/viem/src/actions/executeL2ToL2Message.spec.ts, packages/viem/src/actions/sendL2ToL2Message.spec.ts, packages/viem/src/utils/extractMessageIdentifierFromLogs.ts, packages/wagmi/src/hooks/useWaitForMessageIdentifier.ts
* Updates tests to latest gensis file in supersim to get interop contract changes
* Adds latest abi for `L2ToL2CrossDomainMessenger` and `CrossL2Inbox`
* Code changes required for parsing initiating and executing messages
=> Update to latest interop message changes

apps/dapp-console-api/src/constants/faucetConfigs.ts
Adds [Metal](https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/configs/sepolia/metal.toml) to `dapp-console-api` faucet config with staging support
=> Add Metal to faucet config

apps/dapp-console-api/src/constants/faucetConfigs.ts
Enables metal on the faucet in prod
=> enable metal in prod

packages/viem/package.json, packages/wagmi/package.json
Marks viem & wagmi packages as public
=> mark wagmi and viem packages as public

packages/viem/README.md, packages/viem/docs/guides/interop.md, packages/viem/docs/utils/extractMessageIdentifierFromLogs.md, packages/wagmi/README.md, packages/wagmi/docs/useExecuteL2ToL2Message.md, packages/wagmi/docs/useSendL2ToL2Message.md
* Updates `viem` docs to point directly to github so our npm homepage can find it since we're not bundling them with our package.
* Adds `wagmi` docs
=> Update Wagmi & Viem Docs

.changeset/purple-rocks-destroy.md
Adds initial changeset to publish `0.0.1` version, snapshots are already being published on `main` merges
=> adds initial changeset for viem & wagmi

apps/dapp-console/app/faucet/components/ClaimButton.tsx, apps/dapp-console/app/faucet/components/FaucetContent.tsx, apps/dapp-console/app/hooks/useFaucetVerifications.ts
Part of https://github.com/ethereum-optimism/ecosystem/issues/449
=> feat(dapp-console): disable claim flow when user does not have github account linked

apps/dapp-console/app/components/Header/index.tsx
Updated the HeaderLogo component to support a new logo design with dynamic sizing.
=> fix(dev-console): Update header styling

.changeset/violet-carpets-cheer.md, packages/viem/src/utils/l2ToL2CrossDomainMessenger.ts
=> bugfix(viem): wrong comparison operator when filtering logs

apps/dapp-console-api/src/constants/faucetConfigs.ts
* Adds unichain to faucet configs
=> Adds unichain to faucet configs

.changeset/config.json
Remove dapp-console reference in changeset config
=> Remove dapp-console reference in changeset config

.changeset/fuzzy-grapes-prove.md, packages/viem/src/abis.ts
Part of https://github.com/ethereum-optimism/supersim/issues/200
=> feat(viem): update SuperchainWETH abi to latest

.changeset/cuddly-cougars-do.md, packages/wagmi/src/hooks/useCrossChainSendETH.ts, packages/wagmi/src/hooks/useSendSupERC20.ts, packages/wagmi/src/hooks/useSendSuperchainWETH.ts, packages/wagmi/src/index.ts
Updates `@eth-optimism/wagmi` to include the following hooks
* `useSendSupERC20`
* `useSendSuperchainWETH`
* `useCrossChainSendETH`
=> Adds Sending SupERC20 & SupWETH Hooks

packages/viem/src/chains/supersim.ts
=> fix: supersimL2E chain ID

.changeset/short-mails-battle.md, packages/viem/src/addressSet.ts, packages/viem/src/chains/index.ts, packages/viem/src/chains/interopAlpha.ts, packages/viem/src/chains/interopAlphaAddresses.ts, packages/viem/src/chains/supersim.ts, packages/viem/src/chains/supersimAddresses.ts
based on https://docs.optimism.io/stack/interop/tools/devnet
=> feat(viem): add interop-alpha chains

.changeset/cool-forks-burn.md, packages/viem/scripts/chaingen.ts, packages/viem/src/actions/interop/sendETH.spec.ts, packages/viem/src/actions/interop/withdrawSuperchainWETH.spec.ts, packages/viem/src/chains/interopAlpha.ts, packages/viem/src/chains/mainnet.ts, packages/viem/src/chains/sepolia.ts
- Use Pascal case for the chain names
- Remove testnet from the names
- Omit 'Mainnet' unless OP.
- Add Sepolia to the name for the testnet networks
=> viem: prettify the chain names

package.json
This pull request includes a small change to the `package.json` file. The change adds a new script command to create a snapshot version during the release process.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17): Added a new script `release:version:snapshot` to create a snapshot version using the `changeset` tool and an optional `SNAPSHOT_NAME` environment variable.
**Tests**
**Additional context**
**Metadata**
=> fix missed command

.circleci/config.yml
In one of the PR published by changeset a [file](https://github.com/ethereum-optimism/ecosystem/pull/678/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346) that seems to be generated by NX orb is not cleaned up, probably because of an error.
Upgrading to the latest nx orb, also improving the general ci for a more clean build and improved echo messages.
This pull request includes several updates to the `.circleci/config.yml` file to improve the CI/CD pipeline and ensure dependencies are correctly managed. The most important changes include updating orb versions, modifying setup commands, and cleaning up the job steps.
* **Orb Version Updates:**
- Updated `nx` orb from version `1.6.2` to `1.7.0`.
- Updated `ethereum-optimism/circleci-utils` orb from …
=> test changes

.changeset/three-falcons-yawn.md, mise.toml, packages/viem/package.json, packages/viem/src/actions/interop/sendETH.spec.ts
Copy of https://github.com/ethereum-optimism/ecosystem/pull/694/
=> fix(viem): export actions

mise.toml, packages/supersim/install.js, packages/supersim/package.json
Part of https://github.com/ethereum-optimism/supersim/issues/384
=> release(supersim): supersim 0.1.0-alpha.49

apps/autorelayer-interop/README.md, apps/autorelayer-interop/package.json, apps/autorelayer-interop/src/config/config.ts, apps/autorelayer-interop/src/index.ts, apps/autorelayer-interop/src/relayer.ts, apps/autorelayer-interop/src/utils/jsonFetchParams.ts, apps/autorelayer-interop/tsconfig.json, pnpm-lock.yaml
Simple autorelayer leveraging the ponder-interop as the api layer of pending messages
The autorelayer can run in two configurations
- Local relayer by setting a private key
- Sponsored endopint handoff.
=> feat: autorelayer app

.changeset/shiny-buckets-talk.md, packages/utils-app/package.json
Updates the package.json for utils-app so that it will be published to npm:
- Removes private field
- Specifies repo information in package.json
- Defines the main, modules, types, files, and exports fields
=> feat: update utils-app to publish to npm

Dockerfile
=> chore: add extra certs path for docker images

.changeset/hip-rules-wonder.md, apps/autorelayer-interop/eslint.config.js, apps/autorelayer-interop/src/app.ts, apps/autorelayer-interop/src/relayer.ts
Part of https://github.com/ethereum-optimism/ecosystem-private/issues/342
=> feat(autorelayer): add pending message validation hooks to Relayer

.changeset/spicy-kiwis-draw.md, apps/autorelayer-interop/src/relayer.ts, apps/ponder-interop/ponder.schema.ts, apps/ponder-interop/src/index.ts
Part of https://github.com/ethereum-optimism/ecosystem-private/issues/342
=> feat(ponder-interop): add tx origin to indexed L2toL2CDM:SentMessage

.changeset/smart-spies-breathe.md, apps/autorelayer-interop/src/app.ts, apps/autorelayer-interop/src/relayer.ts
Part of https://github.com/ethereum-optimism/ecosystem-private/issues/342
=> feat(autorelayer-interop): make `fetchPendingMessages` overridable

.circleci/config.yml, Dockerfile
Add in build-and-publish circleci workflows for each app.
- Applies only on the main branch
- Not a condition to merging as the check workflow covers the apps successfully building
Followups
- We might want a workflow where we can trigger a build & publish on a dev branch with approval. So that we can get out emergency patches without merging into main
=> feat: docker circleci workflow

.circleci/config.yml, apps/autorelayer-interop/src/app.ts, apps/autorelayer-interop/src/relayer.ts
Better error handling. Use Pino `err` key for better serialization
Aside: prefix docker images with `ecosystem-`
=> fix: autorelayer-interop better error handling
