ethereum-optimism/ecosystem

- packages/op-app/package.json
- packages/op-app/src/hooks/useIsNetworkUnsupported.test.ts
- packages/op-app/src/hooks/useL1PublicClient.test.ts
- packages/op-app/src/hooks/useL2PublicClient.test.ts
- packages/op-app/src/hooks/useOPNetwork.test.ts
- packages/op-app/src/hooks/useOPTokens.test.ts
- packages/op-app/src/hooks/useOPWagmiConfig.test.ts
- packages/op-app/src/hooks/useOPWagmiConfig.ts
- packages/op-app/src/test-utils/chains.ts
- packages/op-app/src/test-utils/constants.ts
- packages/op-app/src/test-utils/react.tsx
- packages/op-app/src/types/index.ts
- packages/op-app/vite.config.ts
- pnpm-lock.yaml
* Adds `test-utils` to `op-app` this configures wagmi with eth mainnet and op mainnet as the default l1 & l2
* Adds unit tests for all hooks in `op-app`
> Add tests for op-app

- apps/bridge-app/package.json
- apps/bridge-app/src/routes/Bridge.tsx
- nx.json
- packages/ui-components/.eslintrc.cjs
- packages/ui-components/.gitignore
- packages/ui-components/package-lock.json
- packages/ui-components/package.json
- packages/ui-components/src/TestComponent.tsx
- packages/ui-components/src/index.tsx
- packages/ui-components/tsconfig.json
- packages/ui-components/tsconfig.test.json
- packages/ui-components/vite.config.ts
- pnpm-lock.yaml
Boiler plate code to create the `ui-components` package. verified that building with vite works when starting up the `bridge-app` & test component loads nicely 💯
> Create ui-components package

- .github/CODEOWNERS
Adds `CODEOWNERS` file and makes ecopod the default codeowners
> Adds CODEOWNERS file

- .gitignore
- apps/paymaster-proxy/README.md
- apps/paymaster-proxy/example.env
- apps/paymaster-proxy/package.json
- apps/paymaster-proxy/scripts/generateExampleEnv.ts
- apps/paymaster-proxy/src/app.ts
- apps/paymaster-proxy/src/envVars.ts
- apps/paymaster-proxy/src/envVarsSchema.ts
- apps/paymaster-proxy/tsconfig.json
- pnpm-lock.yaml
- adds a script to generateExampleEnv that uses the envVarsSchema to generate a `example.env` file - this existed while back in the previous repo
- adds a basic envVars file with `HOST` and `PORT` that will be used for express server
- updated README.md file with minimal getting started instructions
> feat(paymaster-proxy): add envVars and example.env generation

- Dockerfile
- apps/paymaster-proxy/docker-compose.yml
- apps/paymaster-proxy/example.env
- apps/paymaster-proxy/src/app.ts
- apps/paymaster-proxy/src/envVarsSchema.ts
- adds a docker-compose for testing docker build 
- adds `/healthz` and `/ready` route for k8s
- hardcodes HOST in the code instead of relying on envvar
> feat(paymaster-proxy): add healthcheck/readiness routes and simple docker-compose

- .circle/config.yml
- created a `docker-build` job that is similar to our existing one but also takes a `docker_target` for multi-stage builds
- created a `docker-publish` job that pushes to our gcr repo after authenticating - same as existing config on monorepo
- only runs on merges to `main`
> ci:(monorepo): add CircleCI config for building and publishing docker images

- .circleci/config.yml
setup_remote_docker job is only available on docker executor
> fix(ci): update machine to docker executor to use layer caching

- apps/paymaster-proxy/loadtest/basic-loadtest.yml
- apps/paymaster-proxy/package.json
- apps/paymaster-proxy/src/app.ts
- apps/paymaster-proxy/src/middlewares/rateLimiter.ts
- pnpm-lock.yaml
- added basic rate limiting with the `express-rate-limit` API
- the rate limit cache is in memory per pod, not shared between pods yet. In a subsequent PR, will add support for storing rate limit state in Redis.
- added a config for running loadtest through https://github.com/artilleryio/artillery
- used it to test that the rate limit works correctly - confirmed that the endpoint begins to return 429
- in practice we will run it against the deployed service not the locally running instance - but keeping config in the repo since it might be useful
> feat(paymaster-proxy): add basic in-memory rate limiting

- .gitignore
- Dockerfile
- apps/paymaster-proxy/docker-compose.yml
- certs/.gitignore
- certs/README.md
- mounts extra-ca-certificates.cert to `usr/local/share/ca-certificates/extra-ca-certificates.crt`
- passes the extra certificates path to env so node picks it up
- fine if the file doesn't exist, app still runs as errors are ignored (warning is emitted though like the following)
```
Warning: Ignoring extra certs from `/usr/local/share/ca-certificates/extra-ca-certificates.crt`, load failed: error:80000002:system library::No such file or directory
```
> build(paymaster-proxy): pull in certs in Dockerfile

- apps/dapp-console/app/console/components/ProjectIconLinks.tsx
- apps/dapp-console/app/page.tsx
- packages/ui-components/src/components/ui/card.tsx
Implementation of the header section for the console page.
Image background still is a placeholder until we get the finalized image from the brand team.
> Implement console header section

- .github/actions/setup/action.yml
- .github/workflows/main.yml
Updates the entire build to swap from `run-many` to `affected`. This will now only `build`, `lint`, `test`, `typecheck` only packages that have a change inside of them. We'll need to verify this is working correctly when building on the `main`, I tested out changes to `op-app` to see if it would build both `op-app` and `bridge-app` since they are part of the same tree and all looked good. We won't notice any real speed gains initially since we don't have much in the repo but starting this type of logic early will help keep this running smooth in the long run
Nx docs https://nx.dev/ci/features/affected
> swap run-many to affected

- packages/op-app/src/test-utils/chains.ts
The environment variable we were using to figure out the vitest test pool was incorrect looks like its from a bad find and replace. This PR just fixes it to be `VITEST_POOL_ID` like expected, otherwise we are always defaulting to `1` which might not always exist
> Fixes incorrect vitest test pool env var

- apps/dapp-console/app/console/components/BuildSection.tsx
- apps/dapp-console/app/console/components/LaunchSection.tsx
- apps/dapp-console/app/console/constants.tsx
- apps/dapp-console/app/console/useDialogContent.tsx
- apps/dapp-console/app/constants/index.tsx
- Implemented Build section modals 
- Implemented Launch & grow modals
I created a hook to organize the content for these modals in a maintainable + reusable way to keep this surface future-proof. Take a look at `useDialogContent` for the code. Since a little over half of the modals are dynamic based on the user being signed in, I am conditionally rendering the content buttons w/ the `authenticated` state with `usePrivy`.
https://github.com/ethereum-optimism/ecosystem/assets/10838132/095094e6-3073-4ea4-9144-c9666e66c1f8
> Implement Build + Launch & Grow modals

- apps/dapp-console/app/components/Header/HeaderTabs.tsx
- apps/dapp-console/app/components/Header/MobileMenu.tsx
- apps/dapp-console/app/components/Header/ThemeToggle.tsx
- apps/dapp-console/app/components/Header/index.tsx
- apps/dapp-console/app/constants/index.tsx
Implemented mobile nav menu for dapp-console.
- Implemented a custom menu icon with `framer-motion` since the remix one switching from the menu to x was ugly.
- Designed this as a sliding menu that turns into full width on sm screens.
- Implemented the support dropdown with our `Accordion` component.
- There was no design for the mobile menu so I just took a stab at what I think it should look like based on the desktop view-- if there are any modifications that we should make i'm happy to include them
https://github.com/ethereum-optimism/ecosystem/assets/10838132/d285ea1c-fc64-49cc-9d7b-00c50e53b5cc
> Implemented mobile nav menu

- apps/paymaster-proxy/docker-compose.yml
- apps/paymaster-proxy/example.env
- apps/paymaster-proxy/package.json
- apps/paymaster-proxy/src/envVars.ts
- apps/paymaster-proxy/src/envVarsSchema.ts
- apps/paymaster-proxy/src/errors/JsonRpcError.ts
- apps/paymaster-proxy/src/helpers/screenAddress.spec.ts
- apps/paymaster-proxy/src/helpers/screenAddress.ts
- apps/paymaster-proxy/src/rpc/getJsonRpcRequestHandler.ts
- apps/paymaster-proxy/src/schemas/addressSchema.ts
- apps/paymaster-proxy/src/schemas/createJsonRpcResponseSchema.ts
- apps/paymaster-proxy/src/testUtils/getRandomAddress.ts
- apps/paymaster-proxy/src/testUtils/mswServer.ts
- apps/paymaster-proxy/src/testUtils/setup.ts
- apps/paymaster-proxy/src/testUtils/testEnvVars.ts
- apps/paymaster-proxy/vitest.config.ts
- pnpm-lock.yaml
- adds support for screening sanctioned addresses using internal screening service
- adds msw to help with mocking fetch responses for testing
- updates docker compose to use the local .env file
- tested inside local docker container to check that certs work correctly - using a sanctioned address in https://www.treasury.gov/ofac/downloads/sdn_comments.csv
> feat(paymaster-proxy): screen sanctioned addresses

- apps/event-log-indexer/package.json
build step isn't needed for ponder since it runs codegen at runtime.
it was breaking builds with
```
Error: Cannot find module '@ast-grep/napi-linux-arm64-musl'
```
> build(event-log-indexer): remove build command

- apps/paymaster-proxy/package.json
- apps/paymaster-proxy/src/ProxyService.ts
- apps/paymaster-proxy/src/api/getV1ApiRoute.ts
- apps/paymaster-proxy/src/initializeApiServer.ts
- apps/paymaster-proxy/src/monitoring/metrics.ts
- apps/paymaster-proxy/src/paymaster/alchemy/getAlchemyPaymasterConfig.ts
- apps/paymaster-proxy/src/rpc/getJsonRpcRequestHandler.ts
- pnpm-lock.yaml
Adds pino logger which is used to log error and info.
nice thing about pino logger is you can create instances with logger.child({ }) with default params allowing you to easily namespace logs. maybe as a future add on i might create something similar for our prom metrics as well (inspired by https://pkg.go.dev/github.com/prometheus/client_golang@v1.8.0/prometheus#MetricVec.CurryWith)
Logging all important failures / address screenings
> feat(paymaster-proxy): add pino logger

- Dockerfile
- apps/event-log-indexer/.gitignore
- apps/event-log-indexer/docker-compose.yml
- apps/event-log-indexer/generated/schema.graphql
- apps/event-log-indexer/package.json
- apps/event-log-indexer/setup-local-db.sql
* Updates `Dockerfile` to generate ponders image
* Adds docker compose setup to spin up a local postgres, and new image locally
* Adds `setup-local-db.sql` to mimic having `read_only` and `read_write` roles in our deployed GCP dbs and hopefully avoiding permission errors when ponder attempts to create a new schema
* Checks in generated graphql schema so we know exactly what schema each image version is running
> event-log-indexer docker & docker-compose setup

- apps/dapp-console/app/components/Header/HeaderTabs.tsx
- apps/dapp-console/app/components/Header/SignInButton.tsx
- apps/dapp-console/app/console/components/BuildSection.tsx
- apps/dapp-console/app/console/components/LaunchSection.tsx
- apps/dapp-console/app/console/components/PromotionsSection.tsx
- apps/dapp-console/app/console/components/SupportSection.tsx
- apps/dapp-console/app/console/constants.tsx
- apps/dapp-console/app/event-tracking/mixpanel.tsx
- apps/dapp-console/app/providers/PrivyProviderWrapper.tsx
closes https://github.com/ethereum-optimism/ecosystem/issues/104
This PR adds the individual events and tracking calls for each of the Dapp Console user actions we want to track. More detailed information on the tracking can be found here: https://docs.google.com/document/d/1iJeKa9o3cRnIO0yxxwnDgFaP8nr_hocsBKr6tDlWKD0/edit#heading=h.lnsjyxig3l7x
This is the list of events added:
```
enum TRACKING_EVENT_NAME {
PageVisit = 'Page Visit',
SignInClick = 'Sign In Click',
SuccessfulSignIn = 'Successful Sign In',
CardClick = 'Card Click',
TopBarClick = 'Top Bar Click',
SupportDocsClick = 'Support Docs Click',
OfferEngaged = 'Offer Engaged',
}
```
> Adding tracking events for dapp console

- apps/paymaster-proxy/package.json
- apps/paymaster-proxy/src/ProxyService.ts
- apps/paymaster-proxy/src/initializeApiServer.ts
- apps/paymaster-proxy/src/paymaster/alchemy/getAlchemyPaymasterConfig.ts
- apps/paymaster-proxy/src/rpc/wrapPaymasterResponseIntoJsonRpcResponse.ts
- pnpm-lock.yaml
- adds cors middleware to allow all origins. I assume most people will be using the paymaster through their client frontend.
- slightly updates return value from RPC
> feat(paymaster-proxy): add cors middleware

- apps/paymaster-proxy/src/initializeApiServer.ts
k8s controller receiving 429 on healthcheck / readiness and killing containers because of rate limiting. caused crashloopbackoff
the readiness check isn't resource intensive rn so easiest just to return before rate limiter
> fix(paymaster-proxy): place healthcheck/readiness before rate limit

- apps/dapp-console/app/components/Header/SignInButton.tsx
- apps/dapp-console/app/components/Header/index.tsx
- apps/dapp-console/app/constants/index.tsx
- apps/dapp-console/app/settings/account/page.tsx
- apps/dapp-console/app/settings/components/SettingsCard.tsx
- apps/dapp-console/app/settings/components/SettingsMenu.tsx
- apps/dapp-console/app/settings/contracts/page.tsx
- apps/dapp-console/app/settings/layout.tsx
- apps/dapp-console/app/settings/types.tsx
- apps/dapp-console/app/settings/wallets/page.tsx
- packages/ui-components/src/components/ui/text.tsx
* Adds env var to decide if we should display settings page or not `NEXT_PUBLIC_ENABLE_SETTINGS`. Next PR will add growthbook and we can migrate the setting over on that PR
* Adds directory structure for settings page to get next routing working
* Adds redirect to `/` on logo click
* Fixes text ui component importing `ReactNode`
I'm not trying to match the mocks on this PR, just getting the pages all laid out and testing out Privy
**Contracts**
Route: `/settings/contracts`
**Account**
Route: `/settings/account`
**Wallets**
Route: `/settings/wallets`
> [Dapp Console] Adds Initial Settings Page

- packages/api-plugin/src/generators/trpc-api-generator/files/example.env
- packages/api-plugin/src/generators/trpc-api-generator/files/package.json
- packages/api-plugin/src/generators/trpc-api-generator/files/src/Service.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/api/AdminApi.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/auth/admin.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/auth/index.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/constants/envVars.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/constants/session.ts
This ensures that only admins can access the trpc playground
> Add admin check for accessing playground and admin endpoints to trpc-api generator

- apps/dapp-console/.eslintrc.cjs
- apps/dapp-console/app/components/Header/SignInButton.tsx
- apps/dapp-console/app/constants/envVars.ts
- apps/dapp-console/app/helpers/featureFlags.ts
- apps/dapp-console/app/hooks/useFeatureFlag.ts
- apps/dapp-console/app/layout.tsx
- apps/dapp-console/app/providers/FeatureFlagProvider.tsx
- apps/dapp-console/app/settings/layout.tsx
- apps/dapp-console/package.json
- pnpm-lock.yaml
Adds feature flag support to dapp console. These PR just wraps growthbook and ports some of our gateway code into the dapp console.
There are two new env vars
* `NEXT_PUBLIC_GROWTHBOOK_ENDPOINT`
* `NEXT_PUBLIC_GROWTHBOOK_ENCRYPTION_KEY` (only needed for the prod endpoint)
when it comes to configuring what endpoint we hit i'm going to configure it like so in netlify
**Production**: prod endpoint, encrypted (honestly not sure why it even needs to be encrypted but thats how the endpoint is setup)
**Deploy Previews**: staging endpoint, not encrypted
**Branch Deploys**: staging endpoint, not encrypted
if anyone wants to use this locally you can grab the values in netlify
> [dapp console] Adds Feature Flag Support

- apps/paymaster-proxy/package.json
- apps/paymaster-proxy/src/paymaster/alchemy/getAlchemyPaymasterConfig.ts
- pnpm-lock.yaml
want to make our API as consistent as possible to other services with `pm_sponsorUserOperation`. Changed the behavior slightly so that any existing gas estimation values are ignored, and returns fresh estimation values. 
previously:
- if a request attaches gas estimation parameters, we override any estimation values that the paymaster service returns
now:
- we ignore the gas estimation parameters passed
in general the previous gas estimation values are likey wrong because they don't take into account the amount of gas used for paymaster verification
in the future we can consider adding support for multipliers (https://docs.alchemy.com/reference/alchemy-requestgasandpaymasteranddata)
> feat(paymaster-proxy): tweak api to ignore included gas estimation parameters

- .circleci/config.yml
Closes https://github.com/ethereum-optimism/ecopod/issues/870
- created a `docker-build` job that is similar to our existing one but also takes a docker_target for multi-stage builds
- created a `docker-publish` job that pushes to our gcr repo after authenticating - same as existing config on monorepo
- both of these jobs only run on merges to main
> ci:(monorepo): add CircleCI config for building and publishing dapp-console api

- apps/dapp-console/next.config.mjs
- apps/dapp-console/package.json
- apps/dapp-console/sentry.client.config.ts
- apps/dapp-console/sentry.edge.config.ts
- apps/dapp-console/sentry.server.config.ts
- pnpm-lock.yaml
Adds support for sentry using it's next plugin. Created a new project in sentry called [dapp-console-frontend](https://optimismpbc.sentry.io/projects/dapp-console-frontend/?project=4506876677324800). Netlify is already configured
Example error from a deploy preview: https://optimismpbc.sentry.io/issues/5048546583/?project=4506876677324800&query=&referrer=project-issue-stream (sourcemaps!)
> [dapp console] Sentry Support

- .circleci/config.yml
The linux image we currently use in our circle config will be deprecated in 09/2024: https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177
Workflow runs successfully with new image: https://app.circleci.com/pipelines/github/ethereum-optimism/ecosystem?branch=harry%2Fupdate_circle_image
> Update circle executor image to a supported ubuntu version

- docs/superchain-paymaster/README.md
- docs/superchain-paymaster/example-aa-sdk.md
- docs/superchain-paymaster/example-permissionless.md
- adds api docs with endpoints and specs
- adds usage examples for aa-sdk and permissionless
> docs(paymaster): add paymaster API docs and example code

- apps/dapp-console/app/components/StandardDialogContent.tsx
- apps/dapp-console/app/console/constants.tsx
- apps/dapp-console/app/console/useDialogContent.tsx
- apps/dapp-console/app/settings/layout.tsx
* Moves all shared dialog styles to `StandardDialogContent` so we can reuse the styles across pages
* Adds `deploymentRebateM2Metadata` that will be displayed when settings are enabled. Once M2 is shipped we'll rename it to `deploymentRebateMetadata`.
* Updates contract page header to include the new dialog
> Deployment Rebate Dialog

- apps/paymaster-nft-mint/src/config.ts
- apps/paymaster-nft-mint/src/constants/fraxtalSepolia.ts
- apps/paymaster-nft-mint/src/envVars.ts
- apps/paymaster-nft-mint/src/hooks/useChainRpcConfig.ts
- apps/paymaster-nft-mint/src/libraries/aa-sdk/AaSdkExample.tsx
- apps/paymaster-nft-mint/src/libraries/aa-sdk/createModularAccountClientWithPaymaster.ts
- apps/paymaster-nft-mint/src/pages/MainPage.tsx
adds modular account examples for newly added chains (base-sepolia, zora-sepolia, fraxtal-sepolia).
Not all chains have Kernel available yet, so some chains only support modular account
> feat(paymaster-mint): update example with new chains

- apps/dapp-console/app/layout.tsx
- apps/dapp-console/app/settings/components/LinkedWallet.tsx
* Adds the `Toaster` component to our root layout. This allows us to start showing toasts in the app https://ui.shadcn.com/docs/components/toast
* Updates the wallets page to add the copy icon, and display a toast after copying
https://github.com/ethereum-optimism/ecosystem/assets/1761993/1fcea4e5-6348-4330-8563-9ca496d5f752
> [dapp console] Adds copy address and toast support

- README.md
Fixes the README.md tree link text.
> fix: readme tree link text

- apps/dapp-console-api/example.env
- apps/dapp-console-api/package.json
- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/Trpc.ts
- apps/dapp-console-api/src/api/Middleware.ts
- apps/dapp-console-api/src/constants/envVars.ts
- apps/dapp-console-api/src/constants/index.ts
- apps/dapp-console-api/src/constants/privy.ts
- apps/dapp-console-api/src/constants/session.ts
- apps/dapp-console-api/src/middleware/index.ts
- apps/dapp-console-api/src/middleware/isPrivyAuthed.spec.ts
- apps/dapp-console-api/src/middleware/isPrivyAuthed.ts
- apps/dapp-console-api/src/models/entities.ts
- apps/dapp-console-api/src/testhelpers/MockDB.ts
- apps/dapp-console-api/src/testhelpers/MockLogger.ts
- apps/dapp-console-api/src/testhelpers/MockPrivyClient.ts
- apps/dapp-console-api/src/testhelpers/index.ts
- pnpm-lock.yaml
Closes https://github.com/ethereum-optimism/ecopod/issues/887
Closes https://github.com/ethereum-optimism/ecopod/issues/882
This middleware should guard any trpc routes that require privy authentication. This middleware does the following:
- verifies that the request coming from the frontend has a valid access token provided by privy 
- if the access token is valid, then the access token, expiration time, and entity id are written to the iron session
- revalidates the privy access token in the following scenarios:
- the access token expires
- a new access token is sent to the backend
- the `user` key does not exist on the iron session
> feat(dapp-console): set up privy auth middleware

- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/api/Api.ts
- apps/dapp-console-api/src/api/ApiV0.ts
- apps/dapp-console-api/src/middleware/isPrivyAuthed.spec.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/auth/AuthRoute.spec.ts
- apps/dapp-console-api/src/routes/auth/AuthRoute.ts
- apps/dapp-console-api/src/routes/auth/index.ts
- apps/dapp-console-api/src/testhelpers/auth.ts
- apps/dapp-console-api/src/testhelpers/index.ts
- apps/dapp-console-api/src/testhelpers/session.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/Service.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/api/Api.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/monitoring/metrics.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/892
Logs the user out by deleting the user key on the iron session. This assumes that the frontend will handle logging the user out of privy.
> feat(dapp-console): create endpoint for logging user out

- apps/dapp-console/app/settings/components/SettingsMenu.tsx
- apps/dapp-console/app/settings/layout.tsx
This PR adds a mobile settings menu, and cleans up some of the styles in the desktop menu to support dark mode better
**Mobile**
**Light Mode Desktop**
**Dark Mode Desktop**
> [dapp console] Adds mobile settings menu

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
This improves the devx in the ecosystem repo when using a vscode ide. Specifically, this should prevent devs working in this repo using vscode from having to manually trigger linters and prettier as often.
> Add vscode settings to repo

- apps/dapp-console-api/migrations/0008_absurd_magdalene.sql
- apps/dapp-console-api/migrations/meta/0008_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/api/index.ts
- apps/dapp-console-api/src/api/listHelpers.ts
- apps/dapp-console-api/src/api/types.ts
- apps/dapp-console-api/src/api/zodHelpers.ts
- apps/dapp-console-api/src/models/utils.ts
- apps/dapp-console-api/src/models/wallets.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/constants.ts
- apps/dapp-console-api/src/routes/index.ts
- apps/dapp-console-api/src/routes/wallets/WalletsRoute.spec.ts
- apps/dapp-console-api/src/routes/wallets/WalletsRoute.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/890
Adds a `listWallets` endpoint. This endpoint returns a list of active wallets associated with an account based on a `cursor` and `maxPageSize`
> feat(dapp-console): add list wallets endpoint

- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/api/ApiV0.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
- apps/dapp-console-api/src/routes/contracts/index.ts
Adds `listContractsForApp` endpoint, which returns a paginated list of contracts associated with a given `appId` and `entityId`
> feat(dapp-console-api): add `listContractsForApp` endpoint

- apps/dapp-console-api/migrations/0009_aberrant_unus.sql
- apps/dapp-console-api/migrations/meta/0009_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/api/ApiV0.ts
- apps/dapp-console-api/src/api/listHelpers.ts
- apps/dapp-console-api/src/api/types.ts
- apps/dapp-console-api/src/api/zodHelpers.ts
- apps/dapp-console-api/src/models/apps.ts
- apps/dapp-console-api/src/models/contracts.ts
- apps/dapp-console-api/src/models/wallets.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/apps/AppsRoute.ts
- apps/dapp-console-api/src/routes/apps/index.ts
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
- apps/dapp-console-api/src/routes/contracts/index.ts
- apps/dapp-console-api/src/routes/wallets/WalletsRoute.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/925
Adds `listApps` endpoint for listing the active apps owned by an entity.
> feat(dapp-console-api): `listApps` endpoint

- apps/dapp-console-api/src/constants/envVars.ts
- apps/dapp-console-api/src/models/apps.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/apps/AppsRoute.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/925
`createApp` endpoint creates a new app associated with the entity. The client must provide a name for the app.
> feat(dapp-console-api): add `createApp` endpoint

- apps/dapp-console-api/migrations/0012_lucky_captain_universe.sql
- apps/dapp-console-api/migrations/meta/0012_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/models/deploymentRebates.ts
- apps/dapp-console-api/src/models/transactions.ts
- apps/dapp-console-api/src/models/utils.ts
The postgres `bigint` data type only stores up to 8bytes. In order to store uint256 values we should update the data type for any columns that store a uint256 value to `numeric` data type with a precision of 78: [postgres docs](https://www.postgresql.org/docs/current/datatype-numeric.html)
> feat(dapp-console-api): update pg columns holding uint256 values to numeric data type

- apps/dapp-console-api/migrations/0013_crazy_stardust.sql
- apps/dapp-console-api/migrations/meta/0013_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/models/challenges.ts
- apps/dapp-console-api/src/models/contracts.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
- apps/dapp-console-api/src/utils/challenges.ts
- apps/dapp-console-api/src/utils/index.ts
Adds `startVerification` endpoint to the `contracts` route. This endpoint handles creating a challenge for the user when they are going through the contract verification flow.
> feat(dapp-console-api): `startVerification` endpoint

- apps/api-key-service/docker-compose.yml
- apps/api-key-service/drizzle.config.ts
- apps/api-key-service/migrations/0000_broad_justin_hammer.sql
- apps/api-key-service/migrations/meta/0000_snapshot.json
- apps/api-key-service/migrations/meta/_journal.json
- apps/api-key-service/package.json
- apps/api-key-service/scripts/db-migrate.ts
- apps/api-key-service/setup-local-db.sql
- apps/api-key-service/src/models/apiKeys.ts
- pnpm-lock.yaml
adds a `api-keys` table to the api-key-service db
- not running any runtime migrations right now, will add logic to do this once deployment is set up
```
id: uuid('id').defaultRandom().primaryKey(),
entityId: uuid('entity_id').notNull(),
key: varchar('key').notNull(),
state: varchar('state').$type<ApiKeyState>().notNull(),
stateUpdatedAt: timestamp('state_updated_at', { withTimezone: true }),
deletedAt: timestamp('deleted_at', { withTimezone: true }),
createdAt: timestamp('created_at', { withTimezone: true })
.defaultNow()
.notNull(),
updatedAt: timestamp('updated_at', { withTimezone: true })
.defaultNow()
.notNull(),
```
> feat(api-key-service): add api-keys table

- apps/api-key-service/src/models/apiKeys.ts
- apps/api-key-service/src/routes/keys/KeysRoute.spec.ts
- apps/api-key-service/src/routes/keys/KeysRoute.ts
- only supports updating the state of the api key, returns updated value
- returns nothing, delete by ID
- checks whether api key is enabled and returns a `{ isVerified: boolean }` 
- right now it's a simple lookup, but in the future it should handle signature verification
- returns all api keys for an entity
* rows are soft deleted, so all lookup queries filter out keys that are deleted
> feat(api-key-service): add update, delete, list, verify endpoints

- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/api/ApiV0.ts
- apps/dapp-console-api/src/models/deploymentRebates.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
- apps/dapp-console-api/src/routes/rebates/index.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/895
This `totalRebatesClaimed` endpoint returns the total amount of rebates that an entity has claimed.
> feat(dapp-console-api): `totalRebatesClaimed` endpoint

- apps/dapp-console-api/package.json
- apps/dapp-console-api/src/models/wallets.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/wallets/WalletsRoute.ts
- apps/dapp-console-api/src/utils/coinbaseVerification.ts
- apps/dapp-console-api/src/utils/index.ts
- pnpm-lock.yaml
Part of https://github.com/ethereum-optimism/ecopod/issues/890
Adds:
- `syncCbVerification` endpoint which updates wallets in db with most recent cb verification status
- updates `syncWallets` endpoint to update wallets in db with most recent cb verification status
> feat(dapp-console-api): `syncCbVerification` endpoint

- apps/api-key-service/example.env
- apps/api-key-service/package.json
- apps/api-key-service/scripts/generate-example-env.ts
- apps/api-key-service/src/Service.ts
- apps/api-key-service/src/api/Middleware.ts
- apps/api-key-service/src/constants/envVars.ts
- apps/api-key-service/src/utils/retryWithBackoff.ts
- pnpm-lock.yaml
adds `znv` which is adds preprocessing logic for envvars (casting "false" to false), and works well with zod. also supports default values per node_env, which is only used for defining test envvars
added migrations to run stage of service, meaning /healthz should return 200 even before migrations kick off. /ready will return 503 until migrations complete
> feat(api-key-service): add runtime migrations

- apps/dapp-console-api/src/models/wallets.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/wallets/WalletsRoute.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/890
`walletVerifications` returns which verifications that an entity has on their active wallets.
> feat(dapp-console-api): `walletVerifications` endpoint

- .github/actions/setup/action.yml
- Dockerfile
- package.json
- packages/op-app/package.json
- pnpm-lock.yaml
builds were failing post pnpm 9 upgrade because of some change in how github repo packages are fetched. removed the package since we don't use it right now.
to prevent inconsistencies happening with the new pnpm lockfile v9, also require that devs use pnpm 9
1. force devs to use pnpm 9 - see "engine"
2. force corepack to use pnpm 9 - see "packageManager"
3. remove superchain registry dep
> build(monorepo): remove superchain-registry dep and require pnpm 9

- apps/dapp-console-api/migrations/0015_open_mulholland_black.sql
- apps/dapp-console-api/migrations/meta/0015_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/models/deploymentRebates.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
https://github.com/ethereum-optimism/ecopod/issues/890
Updates the logic for calculating the amount of rebates claimed to be based on the amount of rebates claimed by an entity as well as the amount of rebates claimed across the entity's cb verified wallets.
This is calculated by:
1. Summing the total amount of rebates claimed by entity id
2. Getting the max of the sum of the total amount of rebate claims associated with each cb verified wallet (e.g. `Math.max(sum_claimed_by_cb_verified_wallet1, sum_claimed_by_cb_verified_wallet2, sum_claimed_by_cb_verified_wallet3, etc)`)
4. Returns the maximum of step 1 and step 2 (`Math.max(step 1, step2)`) for the total amount claimed
> feat(dapp-console-api): update total rebates claimed to calculate based on entity and verified wallets

- apps/dapp-console-api/migrations/0018_perfect_human_robot.sql
- apps/dapp-console-api/migrations/meta/0018_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/models/apps.ts
- apps/dapp-console-api/src/models/contracts.ts
- apps/dapp-console-api/src/models/deploymentRebates.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
- apps/dapp-console-api/src/utils/rebateEligibility.ts
Part of https://github.com/ethereum-optimism/ecopod/issues/895
the `listCompletedRebates` endpoint returns a list of completed rebates for an entity using cursor pagination.
> feat(dapp-console-api): `listCompletedRebates` endpoint

- apps/dapp-console-api/src/constants/chains.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/929
Extends public client to include a `debug_traceTransaction` request so that `CREATE2` contract deployments can be successfully verified.
> feat(dapp-console-api): add support for contracts deployed by CREATE2

- apps/dapp-console-api/src/models/apps.ts
- apps/dapp-console-api/src/models/contracts.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
- apps/dapp-console/app/types/api.ts
`deleteContract` endpoint performs a soft delete on the contract in the db. This pr also updates the `createContract` endpoint to check if the contract has previously been deleted when creating a new contract.
> feat(dapp-console-api): `deleteContract` endpoint

- packages/contracts-ecosystem/.gitignore
- packages/contracts-ecosystem/script/DeployConsoleApiTestEnv.s.sol
* Adds a forge script called `DeployConsoleApiTestEnv.s.sol` this will deploy 10 create contracts, and a single create2 contract.
Set `DEPLOYER_PRIVATE_KEY` in the `contracts-ecosystem`  `env` file to the deployer address you want. I used the one at index 0 in anvil https://github.com/ethereum-optimism/ecosystem/blob/8bef0131a48cdb21b7207d34803898c92396ddf3/packages/op-app/src/test-utils/anvil.ts#L33
**Run Script**
```
forge script ./script/DeployConsoleApiTestEnv.s.sol --broadcast --rpc-url http://localhost:8545
```
> Dev Console Anvil State

- apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx
- apps/dapp-console/app/settings/components/EligibleForRebateBadge.tsx
- apps/dapp-console/app/settings/contracts/DeployedApp.tsx
- apps/dapp-console/app/settings/contracts/DeployedAppContract.tsx
- apps/dapp-console/app/settings/contracts/page.tsx
I learned today that trpcs react query integration comes with some utilities for helping to manage the cache https://trpc.io/docs/client/react/useUtils. Instead of having to refetch anything from the api we can just use the utils to invalidate the cache and react query will handle the refetching logic.
This PR updates to start using `useUtils` to keep all the different api calls in sync when we make mutations on the contracts page.
> use trpc utils to invalidate cache

- apps/dapp-console-api/src/middleware/isPrivyAuthed.spec.ts
- apps/dapp-console-api/src/middleware/isPrivyAuthed.ts
- apps/dapp-console-api/src/testhelpers/auth.ts
- apps/dapp-console/app/helpers/apiClient.ts
Update the FE & BE to support an `Authorization` header flow. Our deploy previews aren't on the same domain as the backend so the cookie flow won't work on deploy previews, updating our auth flow to support pulling the token from localStorage and passing it up in the `Authorization` header will get us around this.
> add privy token to authorization header

- apps/dapp-console/app/console/constants.tsx
- apps/dapp-console/app/helpers/apiClient.ts
- apps/dapp-console/app/lib/utils.ts
- apps/dapp-console/app/settings/account/page.tsx
- apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx
- apps/dapp-console/app/settings/components/ClaimedRebates.tsx
- apps/dapp-console/app/settings/components/IneligibleRebateDialog.tsx
- apps/dapp-console/app/settings/components/LinkedWallet.tsx
- apps/dapp-console/app/settings/components/SettingsMenu.tsx
- apps/dapp-console/app/settings/components/WalletVerificationMethods.tsx
- apps/dapp-console/app/settings/contracts/AddContractForm.tsx
- apps/dapp-console/app/settings/contracts/DeployedAppContract.tsx
- apps/dapp-console/app/settings/contracts/StartVerificationDialog/FinishVerificationContent.tsx
- apps/dapp-console/app/settings/contracts/StartVerificationDialog/StartVerificationContent.tsx
- apps/dapp-console/app/settings/layout.tsx
* Fixes not passing default trpc headers up with all requests
* Adds a util for getting the rebate block explorer url. It checks to see if the contract is testnet or mainnet then will use op mainnet or sepolia based on that
* Adds loading state to buttons in the create contract, claim rebate, and verification flows
* Adds a min height to the challenge textarea in the verification flow to prevent any sort of bouncing while waiting for the challenge.
* Removes Delete Account Flow
* Input cleanup, prevents the text cursor and outline from appearing on read only inputs
* Cursor cleanup, adds pointer cursor to interactive text
> Adds loading states to create contract, claim rebate, and verification flows

- apps/paymaster-proxy/src/errors/JsonRpcCastableError.ts
- apps/paymaster-proxy/src/errors/JsonRpcError.ts
- apps/paymaster-proxy/src/jsonRpc/JsonRpcRouter.spec.ts
- apps/paymaster-proxy/src/jsonRpc/JsonRpcRouter.ts
- apps/paymaster-proxy/src/jsonRpc/createExpressRouterFromJsonRpcRouter.spec.ts
- apps/paymaster-proxy/src/jsonRpc/createExpressRouterFromJsonRpcRouter.ts
- apps/paymaster-proxy/src/rpc/wrapPaymasterResponseIntoJsonRpcResponse.ts
- apps/paymaster-proxy/src/schemas/createJsonRpcRequestSchema.ts
To improve maintainability, will refactor the paymaster-proxy logic to have cleaner separation between JsonRPC handling logic vs. business logic. the following helpers will be used. the refactor will be in a subsequent PR
```typescript
const jsonRpcRouter = new JsonRpcRouter()
jsonRpcRouter.method(
'subtract',
z.tuple([z.number(), z.number()]),
async ([a, b]) => a - b,
)
const result = await jsonRpcRouter.handle({
jsonrpc: '2.0',
method: 'subtract',
params: [23, 42],
id: 2,
}
// result
{ jsonrpc: '2.0', result: -19, id: 2 }
```
- as part of the refactor, introducing a new JsonRpcRouter class that helps set up rpc method handlers in an express-like way. 
- notice that individual method handler (`.method()` ) does not need to return a JSON rpc response, the logic to wrap it into a correct …
> feat(paymaster-proxy): create JsonRpcRouter

- apps/dapp-console-api/src/Trpc.ts
- apps/dapp-console-api/src/errors/DappConsoleError.ts
- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/apps/AppsRoute.ts
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
Closes https://github.com/ethereum-optimism/ecopod/issues/941
Adds code based errors for the following mutation endpoints:
- `createContract`
- `startVerification`
- `completeVerification`
- `claimDeploymentRebate`
> feat(dapp-console-api): update backend error messages to be code based

- apps/dapp-console/app/console/components/PromotionsSection.tsx
- apps/dapp-console/tailwind.config.ts
- packages/ui-components/src/components/ui/badge/badge.tsx
- packages/ui-components/src/style.css
- packages/ui-components/tailwind.config.js
In this pull request, a badge feature has been added to the 'PromotionsSection' secondary button in 'dapp-console'. Also, tertiary color has been added to the 'tailwind.config' and 'badge.tsx'.
Badge feature has been added in secondary button in 'PromotionsSection.tsx'. Further, HSL colors for 'secondary' and 'tertiary' color categories have been created in 'tailwind.config.ts'. Also, tertiary color has been initialized in 'badge.tsx' and 'style.css'.
> Add in filters + add tertiary color to tokens

- packages/api-plugin/src/generators/trpc-api-generator/files/package.json
- packages/api-plugin/src/generators/trpc-api-generator/files/scripts/generate-example-env.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/Service.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/constants/envVars.ts
- packages/api-plugin/src/generators/trpc-api-generator/files/src/constants/envVarsSchema.ts
- pnpm-lock.yaml
adds the `znv` example envvar generation script to the trpc-api-generator
> chore(trpc-api-generator): add example envvars generation script

- apps/dapp-console-api/migrations/0020_crazy_ultimatum.sql
- apps/dapp-console-api/migrations/meta/0020_snapshot.json
- apps/dapp-console-api/migrations/meta/_journal.json
- apps/dapp-console-api/src/errors/DappConsoleError.ts
- apps/dapp-console-api/src/models/deploymentRebates.ts
- apps/dapp-console-api/src/models/transactions.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.ts
- apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx
This PR fixes the following:
- enables multiple of the same deployment transactions to be added across different entities
- prevents the same deployment transaction hash from being claimed multiple times
> feat(dapp-console-api): fix deployment transaction bugs

- apps/dapp-console/app/components/Banner/DeploymentRebateBanner.tsx
- apps/dapp-console/app/console/components/Announcements.tsx
- apps/dapp-console/app/console/components/LaunchSection.tsx
- apps/dapp-console/app/page.tsx
- apps/dapp-console/app/settings/wallets/page.tsx
* Adds announcement section to home page that will display the deployment rebate banner if the FF is enabled
* Updates deployment rebate card to say "Featured" when the FF is enabled
**Dark Mode**
**Light Mode**
> Deployment Rebate Banner

- apps/paymaster-proxy/.gitignore
- apps/paymaster-proxy/src/e2eTests/alchemyGasManager.spec.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/AlchemyGasManagerAdminClient.spec.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/AlchemyGasManagerAdminClient.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/alchemyGasManagerAdminActions.spec.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/alchemyGasManagerAdminActions.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/getAlchemyGasManagerDefaultRules.spec.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/getAlchemyGasManagerDefaultRules.ts
- apps/paymaster-proxy/src/testUtils/mockAlchemyGasManagerPolicy.ts
- apps/paymaster-proxy/src/testUtils/mswServer.ts
- apps/paymaster-proxy/src/testUtils/setupE2eEnv.ts
- apps/paymaster-proxy/src/utils/getCurrentUnixTimestamp.ts
- apps/paymaster-proxy/vitest.e2e.config.ts
closes https://github.com/ethereum-optimism/ecopod/issues/951
added helper functions for interacting with Alchemy Gas Manager
https://docs.alchemy.com/reference/gas-manager-admin-api-endpoints
- createAlchemyGasManagerPolicy
- getAlchemyGasManagerPolicy
`apps/paymaster-proxy/src/paymasterProvider/alchemy/alchemyGasManagerAdminActions.ts`
- where majority of functionality is
`apps/paymaster-proxy/src/paymasterProvider/alchemy/getAlchemyGasManagerDefaultRules.ts`
- the default policy - still TBD based on product requirements
`apps/paymaster-proxy/src/paymasterProvider/alchemy/AlchemyGasManagerAdminClient.ts`
- thin wrapper to help with dependency injection
> feat(paymaster-proxy): Alchemy gas manager API helper functions

- apps/dapp-console/app/components/Header/SignInButton.tsx
- apps/dapp-console/app/console/components/Announcements.tsx
- apps/dapp-console/app/console/components/LaunchSection.tsx
- apps/dapp-console/app/console/useDialogContent.tsx
- apps/dapp-console/app/helpers/errorReporting.ts
- apps/dapp-console/app/hooks/useFeatureFlag.ts
- apps/dapp-console/app/settings/layout.tsx
* Updates feature flags to support labs emails, you can now pass along a `allowDevs` option so even if the flag is disabled labs employees will still be able to see it and test it
* Renames `useFeature` -> `useFeatureFlag` to avoid export collision with growthbook
* Sends error to sentry if the feature flag value is not valid
> Updates feature flags to support labs emails

- apps/api-key-service/src/index.ts
- apps/api-key-service/src/routes/keys/KeysRoute.ts
- apps/paymaster-proxy/docker-compose.yml
- apps/paymaster-proxy/src/ProxyService.ts
- apps/paymaster-proxy/src/adminApi/createAdminRouter.ts
- apps/paymaster-proxy/src/adminApi/initializeAdminApiServer.ts
- apps/paymaster-proxy/src/apiKeyService/createApiKeyServiceClient.ts
- apps/paymaster-proxy/src/envVarsSchema.ts
- apps/paymaster-proxy/src/models/sponsorshipPolicies.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/AlchemyGasManagerAdminClient.ts
closes https://github.com/ethereum-optimism/ecopod/issues/954
- used to issue one-off API keys
- delete existing API key by key
> feat(paymaster-proxy): create admin routes for creating policies

- apps/dapp-console/app/event-tracking/mixpanel.tsx
- apps/dapp-console/app/settings/components/ClaimRebateDialog.tsx
- apps/dapp-console/app/settings/layout.tsx
* Updates mixpanel tracking to include the contract chain id when claiming a rebate
* Remove redirect on settings page, instead it continues to show an empty page if the flag isn't enabled
> Hopefully thats it

- apps/paymaster-proxy/src/adminApi/createAdminRouter.ts
- apps/paymaster-proxy/src/api/createV1ApiRouter.ts
- apps/paymaster-proxy/src/config/chainConfigByChainId.ts
- apps/paymaster-proxy/src/envVarsSchema.ts
- apps/paymaster-proxy/src/paymasterProvider/alchemy/createMainnetJsonRpcRouterWithAlchemyPaymasterProvider.ts
adds OP Mainnet support for creating / using policies. Main difference between testnet chains vs mainnet chains is that mainnet chains REQUIRES a policyId vs. for testnet it's optional
- will add other chains in a separte PR
> feat(paymaster-proxy): add mainnet support

- apps/api-key-service/migrations/0001_young_thunderbolt_ross.sql
- apps/api-key-service/migrations/meta/0001_snapshot.json
- apps/api-key-service/migrations/meta/_journal.json
- apps/api-key-service/src/models/apiKeys.ts
- apps/api-key-service/src/routes/keys/KeysRoute.spec.ts
- apps/api-key-service/src/routes/keys/KeysRoute.ts
- apps/api-key-service/src/testUtils/toApiKeyObj.ts
adds a column to `api-keys` table to support an optional name parameter. This can be used to save user defined metadata about apikeys
> feat(api-key-service): add optional name

- apps/dapp-console/app/components/Auth/RequireLogin.tsx
- apps/dapp-console/app/console/constants.tsx
PR fixes two small bugs:
- Properly set the `pendingLogin` state to `false` after successful login
- Properly track when the deployment rebate offer is engaged with
> feat(dapp-console): small fixes

- apps/dapp-console-api/package.json
- apps/dapp-console-api/src/routes/contracts/ContractsRoute.ts
- apps/dapp-console-api/src/routes/rebates/RebatesRoute.spec.ts
- apps/dapp-console-api/src/testUtils/anvil.ts
- apps/dapp-console-api/src/testUtils/chains.ts
- apps/dapp-console-api/src/testUtils/constants.ts
- apps/dapp-console-api/src/testUtils/global.ts
- apps/dapp-console-api/src/testhelpers/auth.ts
- apps/dapp-console-api/src/testhelpers/constants.ts
- apps/dapp-console-api/src/testhelpers/index.ts
- apps/dapp-console-api/vitest.config.ts
- pnpm-lock.yaml
Part of https://github.com/ethereum-optimism/ecopod/issues/979
Adds a test for the happy path of the the `claimDeploymentRebate` endpoint and also configures anvil for the `dapp-console-api` app. 
Tests for edge cases will be added in follow-up pr's.
> feat(dapp-console-api): `RebatesRoute` happy path test

- .changeset/flat-laws-cross.md
- .github/workflows/release-snapshot.yml
- apps/paymaster-proxy/package.json
- apps/ui-component-storybook/package.json
- package.json
- packages/api-plugin/package.json
- packages/op-app/package.json
- pnpm-lock.yaml
Adds a new workflow called `release-snaphot` this will publish a snapshot of a **public** package to NPM. This is important to note that if your NPM package is marked as **private** publishing will be skipped even if a changeset exists for it. Now back to the conditions for getting snapshots published when we merge to our `main` branch.
* If a public package has never been published to NPM it will automatically create an entry
* If a changeset exists it will publish the package to NPM (Run `pnpm changeset` this will prompt you with the interactive cli)
This PR also adds/updates the following
* Adds `@changesets/changelog-github` as a root dev dep
* Marks all packages that we dont' want to publish as private. This is everything besides `op-app` and `sdk`
Example (tested …
> Github action to publish snapshots to NPM

- apps/dapp-console/app/insights/page.tsx
- apps/dapp-console/app/page.tsx
- packages/ui-components/src/style.css
This PR adjusts the border radius attribute in ui-components' style.css.
The border radius in the style.css file was changed from 1rem to a more refined 0.5rem. This change specifically affects the --radius variable used in the css.
> Dial down border radius for ui-components

- .gitmodules
- packages/contracts-ecosystem/.gitignore
- packages/contracts-ecosystem/foundry.toml
- packages/contracts-ecosystem/package.json
- packages/contracts-ecosystem/script/DeployFaucet.s.sol
- pnpm-lock.yaml
Part of https://github.com/ethereum-optimism/ecopod/issues/910
Part of https://github.com/ethereum-optimism/ecopod/issues/1036
This PR creates a deployment script that does the following:
- creates Faucet contract
- creates On Chain Auth Module
- creates Off Chain Auth Module
- Configures the On chain and Off chain auth modules on the faucet contract
> feat(contracts-ecosystem): deploy script for faucet contract

- .changeset/config.json
- .changeset/honest-fireants-relate.md
- .github/workflows/release.yml
- package.json
- packages/sdk/package.json
* Adds support for publishing semvar versions of changesets.
* Ignores apps that pull in those public packages. The reason is changeset right now will attempt to [bump the version](https://github.com/changesets/changesets/blob/761b2d3d26b996a91ddfaa91c6887e50145dcbd7/packages/assemble-release-plan/src/determine-dependents.ts#L194-L205) of those apps  
* Bumps `sdk` to latest versions that we published in monorepo
Flow for publishing packages
* When something gets merged into `main` the release github action will check to see what changesets exist. If there are changesets it will automatically open up a versions PR that increments the package versions, . Once this PR gets approved and merged the same release action will then publish this version to npm.
> Semver NPM Publishing

- apps/dapp-console-api/src/routes/faucet/FaucetRoute.ts
- apps/dapp-console/app/faucet/components/FaucetHeader.tsx
- apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx
- apps/dapp-console/app/faucet/page.tsx
- apps/dapp-console/app/hooks/useAuth.ts
- apps/dapp-console/app/hooks/useConnectedWallet.ts
Refactored the authentication flow in `FaucetHeader` and `FaucetHeaderInner` components to decouple authentication logic from the components and use a new custom `useAuth` hook.
- Removed `usePrivy` authentication logic from `FaucetHeader` and `FaucetHeaderInner` components.
- Introduced a new `useAuth` hook to handle login and logout functionality.
- Modified the `FaucetHeaderInner` to use the new `useAuth` hook for login operations.
- Updated authentication state handling to ensure secure and efficient login/logout operations.
> feat(faucet): Wire up privy login to backend

- apps/dapp-console/app/faucet/components/ClaimButton.tsx
- apps/dapp-console/app/faucet/components/FaucetContent.tsx
- apps/dapp-console/app/hooks/useFaucetNetworks.ts
This pull request introduces additional disabled states for the faucet to handle temporarily unavailable networks.
- Added a new hook, `useFaucetNetworks`, to fetch and determine unavailable networks.
- Updated `FaucetContent.tsx` to use the new hook and disable network options that are temporarily unavailable.
- Updated UI to display 'Temporarily unavailable' message for disabled network options.
> feat(faucet): Add check for unavailable networks

- apps/dapp-console/app/faucet/components/ClaimButton.tsx
- apps/dapp-console/app/faucet/components/FaucetContent.tsx
- apps/dapp-console/app/faucet/components/SuccessDialog.tsx
- apps/dapp-console/app/faucet/types.ts
This PR introduces an `onFailed` callback for the `ClaimButton` component, improving error handling for the claiming process. Additionally, the claiming logic has been refactored to use a unified `claimStatus` state in the `FaucetContent` component, simplifying the state management and improving readability.
- Added `onFailed` callback to `ClaimButton` component.
- Refactored `FaucetContent` to use a single `claimStatus` state instead of separate boolean states.
- Updated `SuccessDialog` to handle and display different claim statuses based on the new `claimStatus` state.
- Removed unnecessary logging from `ClaimButton`.
> feat(faucet): Add failed state

- apps/bridge-app/package.json
- apps/bridge-app/src/App.tsx
- apps/bridge-app/src/providers/SupportedNetworks.tsx
- apps/bridge-app/src/routes/Bridge.tsx
- apps/bridge-app/src/routes/Home.tsx
- apps/bridge-app/src/routes/Playground.tsx
- apps/bridge-app/src/routes/TicTacToe.tsx
- pnpm-lock.yaml
* Updates rainbowkit to it's latest version to get it off the beta release.
* Adds a `SupportedNetwork` provider that deals with getting the user on the correct network
* This is the start of updating the bridge app to be a general purpose app that will includes screens for.
* Wagmi & Viem playground
* Bridge reference
* Interop reference using our tic tac toe game
Eventually, there will be a PR that renames this package and updates the deployment pipelines just waiting on that until we get the game built
Tracker: https://github.com/ethereum-optimism/supersim/issues/3
> Update Bridge App Routes

- apps/kyc-faq/src/App.tsx
This pull request simplifies the routing configuration for the KYC FAQ application. The nested routes under the root path have been removed, leaving only the FAQ page. This change ensures that '/' route directly leads to the FaqPage component. Previously, the root path had multiple children routes, which became redundant and unnecessary.
> Move the /faq route to the root of the FAQ site

- apps/bridge-app/package.json
- apps/bridge-app/src/App.tsx
- apps/bridge-app/src/components/bridge/ReviewDepositDialog.tsx
- apps/bridge-app/src/components/bridge/ReviewWithdrawalDialog.tsx
- apps/bridge-app/src/hooks/tictactoe/useCreateGame.ts
- apps/bridge-app/src/hooks/tictactoe/useJoinGame.ts
- apps/bridge-app/src/hooks/tictactoe/useMakeMove.ts
- packages/op-app/package.json
- packages/op-app/src/hooks/useL1PublicClient.ts
- packages/op-app/src/hooks/useL2PublicClient.ts
- pnpm-lock.yaml
* Bumps `wagmi` & `viem` to latest version in `bridge-app` & `op-app`
* Updates types for the package bumps
> Bump wagmi & viem to latest version

- apps/dapp-console-api/src/utils/Faucet.ts
Drip transactions from the console have been getting stuck. This pads the `maxPriorityFee` on the drip transaction in order to see if this causes transactions to not get stuck.
> feat(faucet): pad max priority fee on faucet drip tx

- packages/viem/package.json
- packages/viem/src/abis.ts
- packages/viem/src/contracts.ts
- packages/viem/src/types/interop.ts
- packages/viem/tsconfig.json
- pnpm-lock.yaml
Directory structure is matching the exact same structure as `viem` so there is less work with upstreaming. Module resolution was also updated to match `viem` so it's easier to upstream
* Adds `viem` as a peer dep and dev dep to `@eth-optimism/viem`
* Adds interop predeploys
* Adds `MessageIdentifier` type
> Adds Interop Predeploy Addresses & Abi

- apps/bridge-app/src/components/bridge/ReviewDepositDialog.tsx
We were passing our portal proxy address as the to field into our wagmi hooks LOL this passes in our address instead like it should be.
> Fixes bridging bug

- packages/viem/src/actions/buildExecuteL2ToL2Message.spec.ts
- packages/viem/src/actions/buildSendL2ToL2Message.spec.ts
- packages/viem/src/actions/estimateExecuteL2ToL2MessageGas.spec.ts
- packages/viem/src/actions/estimateSendL2ToL2MessageGas.spec.ts
- packages/viem/src/actions/executeL2ToL2Message.spec.ts
- packages/viem/src/actions/sendL2ToL2Message.spec.ts
- packages/viem/src/decorators/publicL2.ts
- packages/viem/src/decorators/walletL2.ts
- packages/viem/src/test/clients.ts
* Adds `walletL2` & `publicL2` decorators that allow end users to extend public & wallet clients
* Update tests to use decorators
```
import { publicActionsL2, walletActionsL2 } from '@eth-optimism/viem'
export const publicClient = createPublicClient({
chain: optimism,
transport: http(RPC_URL),
}).extend(publicActionsL2())
export const walletClient = createWalletClient({
account,
chain: optimism,
transport: http(RPC_URL),
}).extend(walletActionsL2())
const args = publicClient.buildSendL2ToL2Message({ ... }) 
await walletClient.sendL2ToL2Message(args)
```
> Adds walletL2 & publicL2 decorators

- apps/bridge-app/package.json
- apps/bridge-app/src/App.tsx
- apps/bridge-app/src/components/NetworkSelector.tsx
- apps/bridge-app/src/routes/TicTacToe.tsx
- packages/viem/src/chains/supersim.ts
- packages/viem/src/index.ts
- pnpm-lock.yaml
* Adds chain defs for supersim in non fork mode to `@eth-optimism/viem`
* updates bridge app to bring in `@eth-optimism/viem` & `@eth-optimisim/wagmi`
* Adds support for configuring wagmi, and the network switcher to support supersim when `VITE_SUPERSIM_ENABLED` is set to `true`
* Adds supersim chains to the supported tic tac toe list
> Add supersim support to bridge app

- apps/dapp-console-api/package.json
- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/constants/envVars.ts
- apps/dapp-console-api/src/growthbook/GrowthbookStore.ts
- apps/dapp-console-api/src/growthbook/index.ts
- apps/dapp-console-api/src/routes/faucet/FaucetRoute.spec.ts
- apps/dapp-console-api/src/routes/faucet/FaucetRoute.ts
- apps/dapp-console-api/src/testhelpers/MockGrowtbookStore.ts
- pnpm-lock.yaml
Part of https://github.com/ethereum-optimism/ecosystem/issues/449
Updates the dapp-console-api to require that claims using `PRIVY` auth must also have a github account associated with their privy user when the `enable_github_auth` feature flag is enabled.
> feat(dapp-console-api): require github auth for faucet claims using privy auth

- apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx
- apps/dapp-console/app/hooks/useAuth.ts
- apps/dapp-console/app/hooks/useFaucetVerifications.ts
- apps/dapp-console/app/hooks/useFeatureFlag.ts
Closes https://github.com/ethereum-optimism/ecosystem/issues/449
Updates faucet dev console to require a user to link their github account in order to perform an offchain claim from the faucet.
> feat(dapp-console): frontend support for requiring github auth when claiming from faucet through privy auth

- apps/dapp-console/app/faucet/components/ClaimButton.tsx
- apps/dapp-console/app/faucet/components/FaucetContent.tsx
- apps/dapp-console/app/faucet/components/SuccessDialog.tsx
- apps/dapp-console/app/hooks/useFaucetVerifications.ts
Closes https://github.com/ethereum-optimism/ecosystem/issues/456
Improves the faucet claim dialog to properly display the claim failed state if the claim tx fails. This will prevent the claim spinner from endlessly spinning when claim txs fail.
> feat(dapp-console): improve error handling on faucet claim flow

- apps/dapp-console-api/src/monitoring/metrics.ts
- apps/dapp-console-api/src/routes/faucet/FaucetRoute.spec.ts
- apps/dapp-console-api/src/routes/faucet/FaucetRoute.ts
- apps/dapp-console-api/src/utils/Faucet.ts
- apps/dapp-console-api/src/utils/faucetBalances.ts
Part of https://github.com/ethereum-optimism/ecosystem/issues/448
This PR enables the dev console backend to fetch the balance of the admin wallet. If the balance of the admin wallet is below .01 ETH, then the faucet will be marked as unavailable.
> feat(dapp-console-api): fetch admin wallet balance for faucet

- apps/dapp-console/app/faucet/components/FaucetHeader.tsx
- apps/dapp-console/app/faucet/components/FaucetHeaderInner.tsx
- apps/dapp-console/app/hooks/useAuth.ts
- apps/dapp-console/app/hooks/useFaucetVerifications.ts
Part of https://github.com/ethereum-optimism/ecosystem/issues/449
Previously github auth was only required for users authing with privy and no on chain method of auth. This change makes it so that even users authenticated with an on chain method must also be authenticated with github.
> feat(dapp-console): require github auth for all auth methods

- apps/dapp-console-api/src/constants/session.ts
- apps/dapp-console-api/src/middleware/index.ts
- apps/dapp-console-api/src/middleware/isGithubAuthed.spec.ts
- apps/dapp-console-api/src/middleware/isGithubAuthed.ts
- apps/dapp-console-api/src/routes/auth/AuthRoute.ts
- apps/dapp-console-api/src/routes/faucet/FaucetRoute.spec.ts
- apps/dapp-console-api/src/routes/faucet/FaucetRoute.ts
Part of https://github.com/ethereum-optimism/ecosystem/issues/449
Server side changes to enforce that users of the faucet have a github account linked to their privy account. This also updates the github account information to be stored in the session instead of fetching it from privy on each request.
> feat(dapp-console-api): check that faucet user has github account linked

- .changeset/thin-carpets-cry.md
- packages/viem/README.md
- packages/viem/docs/utils/decodeSentMessage.md
- packages/viem/src/actions/sendL2ToL2Message.spec.ts
- packages/viem/src/index.ts
- packages/viem/src/utils/decodeSentMessage.ts
* Adds `decodeSentMessage` as a util to `@eth-optimisim/viem`
> Adds decodeSentMessage

- lib/.gitignore
- package.json
- scripts/pull-contract-artifacts.sh
Adds a new command `pnpm fetch:artifacts`. This command expects `gcloud` and `gsutil` to be setup on your box which the ecopod team should already have setup ahead of time.
This script will do the following
* Prompt you to login through your browser and go thru Google OAuth and hit your yubikey
* Once it validates you have access to the artifact it will fetch the latest v1 artifact bundle
* It will then extract the `forge-artifacts` and place them under `lib`
Eventually each package can implement a `generate` command and the scripts to autogenerate our abi, predeploys, viem & wagmi code can all be configured to look at this directory for the latest forge artifacts
> Adds script to fetch the latest forge artifact bundle

- apps/dapp-console-api/src/Service.ts
- apps/dapp-console-api/src/api/AdminApi.ts
- apps/dapp-console-api/src/routes/admin/FaucetAdminRoute.ts
- apps/dapp-console-api/src/routes/admin/index.ts
Part of https://github.com/ethereum-optimism/devx/issues/132
Adds a new admin endpoint for flushing stuck transactions for the Faucet Admin wallet.
> feat(dapp-console-api): add `FaucetAdminRoute` endpoint for flushing pending admin wallet txs

- packages/viem/.gitignore
- packages/viem/src/test/globalSetup.ts
- packages/viem/src/test/startSupersim.ts
Updates our supersim viem logic to wait for the blob of text that says it's ready, and adds utility helpers for local development so it generates two texts files `stdout.txt` and `stderr.txt`
> Wait for supersim to be ready

- .changeset/bright-beans-tell.md
- packages/supersim/install.js
Bumps supersim package to fetch version `0.1.0-alpha.31`
> Bump supersim to pull 0.1.0-alpha.31

- .changeset/empty-terms-admire.md
- packages/viem/scripts/chaingen.ts
- packages/viem/src/chains/mainnet.ts
remove Mainnet as a chain export suffix
changeset
> nit(viem): remove Mainnet as a suffix for exported chains

- packages/viem/src/actions/interop/index.ts
- packages/viem/src/actions/interop/relayMessage.spec.ts
- packages/viem/src/actions/interop/relayMessage.ts
- packages/viem/src/actions/interop/sendETH.spec.ts
- packages/viem/src/actions/interop/sendETH.ts
- packages/viem/src/actions/interop/sendMessage.spec.ts
- packages/viem/src/actions/interop/sendMessage.ts
- packages/viem/src/decorators/publicL2.ts
- packages/viem/src/decorators/walletL2.ts
- packages/viem/src/test/e2e/interop.spec.ts
with scope decorators & actions, no need for the L2ToL2 in the name
> feat: remove L2ToL2 naming for interop actions

- .changeset/five-coins-cheat.md
- packages/supersim/install.js
Bumps supersim to `0.1.0-alpha.32`
> bumps supersim to pull 0.1.0-alpha.32

- .changeset/brave-phones-tie.md
- packages/viem/src/chains/supersim.ts
- packages/viem/src/chains/supersimAddresses.ts
we should generate these long term from https://github.com/ethereum-optimism/supersim/blob/main/genesis/generated/ but these are usually stable even when we update the genesis files.
> feat(viem): update supersim chain definitions and add addresses

- .changeset/brave-cats-sing.md
- package.json
- packages/supersim/install.js
- pnpm-lock.yaml
- scripts/update-supersim-version.ts
when running 
```
pnpm update:supersim 0.1.0-alpha.36
```
it will
1. check that that release is available on github releases
2. generate a changesets file
3. update install.js with correct version
this will help align our npm package version to the goreleaser version
> feat: add script to bump supersim version

- apps/ui-component-storybook/package.json
- mise.toml
- pnpm-lock.yaml
This pull request includes a small change to the `mise.toml` file. The change downgrades the Node.js version from `20.11.0` to `18.18.0`.
Fixing error in CI:
**Tests**
**Additional context**
**Metadata**
> chore: update Node.js version to 18.18.0

- .prettierignore
- README.md
- apps/ponder-interop/package.json
- apps/ponder-interop/ponder-env.d.ts
- apps/ponder-interop/ponder.config.alphanet.ts
- apps/ponder-interop/ponder.config.devnet.ts
- apps/ponder-interop/ponder.config.supersim.ts
- apps/ponder-interop/ponder.config.ts
- apps/ponder-interop/src/api/index.ts
- apps/ponder-interop/src/createPonderConfig.ts
- apps/ponder-interop/tsconfig.json
- pnpm-lock.yaml
For people running this app against a seperate network, we dont want them to edit the code for config.
So the default config is bootstrapped from env.
- dev:(alphanet|devnet|supersim) command to autostart known networks.
- Consolidate ponder config generation between the different ways to configure this.
Aside:
- add the url to the chains api so other apps can just bootstrap from this (autorelayer)
- fix api responses
> chore: start ponder-interop from env

- .changeset/few-tools-tie.md
- apps/ponder-interop/package.json
- apps/ponder-interop/ponder.schema.ts
- apps/ponder-interop/tsconfig.json
- pnpm-lock.yaml
Publishes ponder.schema.ts to npm so that consuming packages can build queries against the indexed interop events.
> feat(ponder-interop): publish ponder.schema.ts to npm

- apps/ponder-interop/package.json
ponder cli runs the source directly
> fix: ponder-interop should bundle the entire codebase

- .changeset/dull-students-reply.md
- apps/ponder-interop/ponder.schema.ts
- apps/ponder-interop/src/index.ts
- apps/ponder-interop/src/utils/hashMessageIdentifier.ts
Closes https://github.com/ethereum-optimism/ecosystem-private/issues/351
With re-emitted messages it is possible for two `SentMesage` events to have identical message hashes. With the primary key of the `l2_to_l2_cdm_sent_messages` ponder table being the message hash, it does not support inserting re-emitted messages. To fix this, this PR updates the primary key of the `l2_to_l2_cdm_sent_messages` to be a hash of the `MessageIdentifier`. 
**Note**: the primary key for the `l2_to_l2_cdm_relayed_messages` can remain as the message hash, since messages cannot be relayed more than once.
> feat(ponder-interop): use hash of message identifier as primary key on `l2_to_l2_cdm_sent_messages` table

- apps/ponder-interop/src/api/index.ts
Part of https://github.com/ethereum-optimism/ecosystem-private/issues/342
The /schema endpoint exposes the current schema that the ponder instance is on. This is helpful for any clients running queries against the ponder db, so that they can be aware of which schema to run their queries against.
> feat(ponder-interop): /schema endpoint

- .changeset/sixty-chairs-teach.md
- apps/autorelayer-interop/docker-compose.yml
- apps/autorelayer-interop/package.json
- apps/autorelayer-interop/src/app.ts
- apps/autorelayer-interop/src/relayer.ts
Closes https://github.com/ethereum-optimism/ecosystem/issues/854
- adds env var `GAS_TANK_ADDRESS` that when set will relay messages via gas tank and points to gas tank contract
- refactors and updates relay logic to relay through gas tank when `GAS_TANK_ADDRESS` is defined
- adds `docker-compose.yml` for `autorelayer-interop`
For now this just relays all messages through the gas tank when the `GAS_TANK_ADDRESS` var is defined regardless of whether or not the gas tank actually is funded for that message. Balance checking will be handled in subsequent PR.
> feat(autorelayer-interop): relay messages via GasTank

- .changeset/shy-ties-hunt.md
- apps/ponder-interop/docker-compose.yml
- apps/ponder-interop/src/api/index.ts
- apps/ponder-interop/src/constants/envVars.ts
Part of https://github.com/ethereum-optimism/ecosystem/issues/839
- Adds `/messages/pending/gas-tank` endpoint to ponder api, which returns all pending messages that have been authorized to be relayed and that contain a gas provider balance > 0
> feat(ponder-interop): add endpoint for fetching pending messages from gas tank

- .changeset/cyan-kids-trade.md
- apps/ponder-interop/ponder.schema.ts
- apps/ponder-interop/src/api/index.ts
- apps/ponder-interop/src/index.ts
Part of https://github.com/ethereum-optimism/ecosystem/issues/840
- Updates the `gas_tank_relayed_message_receipts` to store the message identifier and log payload of the `RelayedMessageGasReceipt` event
- Adds the `/messages/pending/claims` endpoint to the ponder api, which returns a list of relayed messages that should be claimed from the `GasTank`
> feat(ponder-interop): api endpoint for fetching pending GasTank claims

- .changeset/sixty-zebras-brush.md
- apps/autorelayer-interop/src/relayer.ts
Closes https://github.com/ethereum-optimism/ecosystem-private/issues/397
- When determining whether to relay a pending message deducts the pending withdrawals from the gas provider balance and then checks that balance against the estimated gas cost prior to relaying
- When determining which gas provider to use for claiming a relay receipt, first checks if there is a sufficient balance while also accounting for withdrawals, then falls back to checking for the highest raw gas tank provider balance
> feat(autorelayer-interop): deduct pending withdrawals from gas provider balance

- .changeset/curvy-wolves-relax.md
- .changeset/shaggy-boxes-notice.md
- .changeset/two-turtles-reply.md
- apps/autorelayer-interop/src/relayer.ts
- apps/ponder-interop/ponder.schema.ts
- apps/ponder-interop/src/api/index.ts
- apps/ponder-interop/src/index.ts
- packages/viem/src/abis/experimental/index.ts
The `GasTank` abi was recently updated such that now the `GasProvider` is specified at the time of relay, rather than at the time of claiming a message. This change was needed in order to ensure that the a relay receipt could not be claimed multiple times.
- (viem): Update the `GasTank` abi
- (ponder-interop): Index the `GasProvider` from the `RelayMessageReceipt`
- (ponder-interop): update pending claims API endpoint to just return the relay receipt
- (autorelayer-interop): update relays to group by gas provider and specify gas provider when relaying message
> feat(relayer): Update relays through the GasTank to specify GasProvider when relaying message

- .changeset/dirty-cats-tap.md
- apps/ponder-interop/src/api/index.ts
Part of https://github.com/ethereum-optimism/ecosystem-private/issues/398
- Adds the `/messages/pending/claims/:gasProvider/:chainId` endpoint to the ponder api, which returns the total pending relay costs that can be claimed against a specified gas provider
> feat(ponder-interop): add api endpoint for fetching pending claims for a given gas provider

- .changeset/good-teachers-itch.md
- apps/autorelayer-interop/src/relayer.ts
Closes https://github.com/ethereum-optimism/ecosystem-private/issues/398
- When calculating the balance for a given `GasProvider` deducts any unclaimed relays from the `GasProvider`s balance
> feat(autorelayer-interop): incorporate pending claims into GasProvider balance calculations

- .changeset/shaggy-eyes-hammer.md
- apps/autorelayer-interop/src/api/ponderApi.ts
- apps/autorelayer-interop/src/app.ts
- apps/autorelayer-interop/src/config/relayerConfig.ts
- apps/autorelayer-interop/src/relayer.ts
- apps/autorelayer-interop/src/schemas/index.ts
- apps/autorelayer-interop/src/types/index.ts
- apps/autorelayer-interop/src/utils/sponsoredTargets.ts
- apps/autorelayer-interop/src/utils/zodHelpers.ts
Closes https://github.com/ethereum-optimism/ecosystem-private/issues/392
- Updates the relayer config to accept a list of sponsored targets in format `<address>:<chain-id>`
- Fetches pending messages to sponsor using the sponsored targets on the config and relays them through the `L2toL2CrossDomainMessenger`
- Started breaking out `relayer.ts` file into separate files
> feat(autorelayer-interop): add support for relaying sponsored messages

- .changeset/curly-buses-draw.md
- apps/autorelayer-interop/src/config/relayerConfig.ts
- apps/autorelayer-interop/src/relayer.ts
- apps/autorelayer-interop/src/schemas/index.ts
- apps/ponder-interop/src/api/index.ts
Closes https://github.com/ethereum-optimism/ecosystem-private/issues/409
- Updates all ponder api endpoints to serialize `BigInt`s as `String` instead of `Number`
- `String` should be used when serializing `BigInt`s in order to avoid potential overflows
- Fixes bug in message relaying where pending messages were not being properly grouped by their gas provider
- `GasProvider`s were being grouped using a `Map`, however this did not have the intended outcome because equality with a `Map` is determined using reference equality and for the `GasProvider` shallow equality is needed. In order to fix, the `Map` was changed to a `Record` with a unique key for each `GasProvider`
> fix(relayer): fix ponder BigInt serialization and fix GasProvider relay grouping
